### ISSUE TITLE
Add an issue template

### ISSUE THREAD

**Issue by gasinvein** [flathub/net.lutris.Lutris#1]
We need some essential info from the user to investigate an issue:

1. Is this an issue with Lutris itself, its runner, or runnable content (i.e. a game)?
2. Is it reproducible with non-flatpak Lutris?
3. Steps to reproduce

**Comment by LeandroStanger** [comment]
Use with example https://github.com/flathub/com.valvesoftware.Steam/blob/master/.github/ISSUE_TEMPLATE/game_issue.md
