### ISSUE TITLE
Steam commandline options

### ISSUE THREAD

**Issue by FakeShemp** [flathub/net.lutris.Lutris#10]
**Describe the problem**
When launching a Steam game with a commandline argument added to the game options, the command will not be sent with the `steam://` link.

**Is it reproducible with native Lutris?**
Probably not.

**Steps to reproduce**
1. Install a game (I chose a Unity game)
2. Add an commandline argument under game options (I used `-force-d3d9`).

**Expected behavior**
Game launching without commandline arguments (game would run with D3D9).

**Actual behavior**
Game launched without commandline argument (in my case with D3D11).

**Flatpak info**
`flatpak --version` 
```
1.2.4
```
`flatpak --gl-drivers`
```
default
host
```

**Comment by gasinvein** [comment]
Please try this https://github.com/flathub/net.lutris.Lutris/pull/11#issuecomment-507407147 test build and check if it fixes the issue.

**Comment by FakeShemp** [comment]
Seems to work exactly like it should. Thank you :)
