### ISSUE TITLE
Feature Request: MangoHUD

### ISSUE THREAD

**Issue by Pixeliz3d** [flathub/net.lutris.Lutris#103]
Can we have [MangoHUD](https://github.com/flightlessmango/MangoHud) overlay extension for Flatpak Lutris like [this](https://github.com/flathub/com.valvesoftware.Steam.Utility.MangoHud)?

**Comment by gasinvein** [comment]
See https://github.com/flathub/com.valvesoftware.Steam.VulkanLayer.MangoHud/issues/6#issuecomment-602568826
