### ISSUE TITLE
Filesystem override doesn't work with only this package

### ISSUE THREAD

**Issue by PureTryOut** [flathub/net.lutris.Lutris#106]
I'm trying to give the container access to a directory on my host system. While `flatpak override com.valvesoftware.Steam --filesystem=/games` worked for Steam, the same doesn't for Lutris (obviously with `com.valvesoftware.Steam` replaced for `net.lutris.Lutris`). `/games` just isn't available in the container.

However, `flatpak run --filesystem=/games net.lutris.Lutris` works. Is this a container issue or something else?

**Comment by A6GibKm** [comment]
Maybe you installed one with the --user flag, in that case you need to pass the --user flag together with override

**Comment by PureTryOut** [comment]
Oh wow, you're right. TIL!
Thanks!
