### ISSUE TITLE
Create extension for OpenLDAP etc.

### ISSUE THREAD

**Issue by plata** [flathub/net.lutris.Lutris#108]
Instead of bundling the runtime libraries, create separate extensions for them.

Advantages:
- other flatpaks can use the extensions as well (e.g. winepak/Phoenicis)
- security vulnerabilities/updates can be handled more easily (e.g. Lutris uses OpenLDAP 2.4.49 but 2.4.50 has been released)
- flatpak yml will be cleaner

**Comment by gasinvein** [comment]
See flathub/flathub#1428, similar solution, but in form of baseapp instead of extension.

**Comment by A6GibKm** [comment]
This was already done, see https://github.com/flathub/org.winehq.Wine
