### ISSUE TITLE
Lutris Does Not Detect Libstrangle

### ISSUE THREAD

**Issue by Saroufim** [flathub/net.lutris.Lutris#113]
Lutris's option to limit the FPS is still greyed out despite the fact that libstrangle is installed on the host system
**Is it reproducible with native Lutris?**
No
**Steps to reproduce**
1. install libstrangle on the base system
2. notice that it is not detected by Lutris

**Expected behavior**
Flatpak Lutris to detect the library

**Flatpak info**
`flatpak 1.6.4`
`flatpak --gl-drivers : host default`

**Comment by A6GibKm** [comment]
Duplicate of #62.

**Comment by Saroufim** [comment]
My, I duplicated myself in a lapse of attention. I will close this one.
