### ISSUE TITLE
Documentation: Missing dep

### ISSUE THREAD

**Issue by ShalokShalom** [flathub/net.lutris.Lutris#117]
`The application net.lutris.Lutris/x86_64/beta requires the runtime org.gnome.Platform/x86_64/3.36 which was not found
`

**Comment by A6GibKm** [comment]
Does this issue still persists?

**Comment by ShalokShalom** [comment]
Is it supposed to be changed since when I posted it?
I can try soon.

**Comment by A6GibKm** [comment]
I updated the runtime to 3.38. I don't know, it would be useful to check if the runtime is getting automatically installed when updating lutris.

**Comment by A6GibKm** [comment]
This is outdated, please re open if the issue persists.
