### ISSUE TITLE
Web runner does not start since it updated

### ISSUE THREAD

**Issue by FakeShemp** [flathub/net.lutris.Lutris#121]
**Describe the problem**
The newest web runner updated electron and I think this broke flatpak support. It could possibly be fixed by `org.electronjs.Electron2.BaseApp` and/or `zypak`.

**Is it reproducible with native Lutris?**
No.

**Steps to reproduce**
1. Install a web app like `lutris:host-master-and-the-conquest-online`
2. Try to run it

**Expected behavior**
Game to start

**Actual behavior**
Nothing

**Flatpak info**
`flatpak --version` 
```
1.8.2
```
`flatpak --gl-drivers`
```
nvidia-450-66
default
host
```

**Comment by gasinvein** [comment]
Does it work with `--no-sandbox` browser argument?

**Comment by FakeShemp** [comment]
Does not look like it

```
lutris-wrapper: Host Master and the Conquest of Humor
Running /home/rebecca/.var/app/net.lutris.Lutris/data/lutris/runners/web/electron/electron /home/rebecca/.var/app/net.lutris.Lutris/data/lutris/runners/web/electron/resources/app.asar http://www.doublefine.com/themes/site_themes/default/flash/GDCgame.swf --name Host Master and the Conquest of Humor --icon /app/share/lutris/media/default_icon.png --window-size 800x600
Initial process has started with pid 25
Game is considered started.
[25:1021/172905.749690:FATAL:setuid_sandbox_host.cc(158)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /home/rebecca/.var/app/net.lutris.Lutris/data/lutris/runners/web/electron/chrome-sandbox is owned by root and has mode 4755.
Game is considered exited.
Initial process has exited.
All children have exited.
Exit with returncode 133
```

**Comment by gasinvein** [comment]
I don't see the argument passed to the command line. Maybe Lutris gust ignores "browser arguments" for their electron binary?

**Comment by FakeShemp** [comment]
Yup, seems custom arguments are only passed to custom browsers.

**Comment by FakeShemp** [comment]
Solved with https://github.com/lutris/lutris/pull/3240
