### ISSUE TITLE
Perl is missing in runtime

### ISSUE THREAD

**Issue by hr567** [flathub/net.lutris.Lutris#136]
**Describe the problem**
Perl is needed by winetricks during software downloaded. But Perl has not been installed in net.lutris.Lutris.

**Is it reproducible with native Lutris?**
Yes

**Steps to reproduce**
1. Install a game with wine runner
2. Open winetricks of the game
3. Install any DLL or font

**Expected behavior**
Winetricks installs the DLL or font in the wine prefix.

**Actual behavior**
Winetricks exited with the following message:
"$HOME/.var/app/net.lutris.Lutris/data/lutris/runtime/winetricks/winetricks:line1091: perl: Command not found" and "warning: sha256sum mismatch! Rename XXX and try again."
WINETRICKS_VERSION=20201206-next

**Flatpak info**
`flatpak --version`
Flatpak 1.9.2
`flatpak --gl-drivers`
nvidia-455-45-01
default
host

**Comment by juligreen** [comment]
I'm able to reproduce this issue.
