### ISSUE TITLE
Dosbox games not running (missing libcaca.so dependency)

### ISSUE THREAD

**Issue by LyzardKing** [flathub/net.lutris.Lutris#138]
**Describe the problem**
When I try and run the game a dosbox game in the flatpak version of Lutris I get the following error and the game fails to start:

> /home/galileo/Games/gog/bio-menace/Game/dosbox/dosbox_x86_64: error while loading shared libraries: libcaca.so.0: cannot open shared object file: No such file or directory

**Is it reproducible with native Lutris?**
No, it works on Lutris native (running on Ubuntu 20.10) since the dependency is available

**Steps to reproduce**
1. Install a dosbox game 
2. Try to start it

**Expected behavior**
The game starts and plays correctly,

**Actual behavior**
I get the error message and the game never starts

**Flatpak info**
`flatpak --version`
Flatpak 1.8.2
`flatpak --gl-drivers`
default
host

**Comment by A6GibKm** [comment]
Could you test #139 when it finishes?

**Comment by LyzardKing** [comment]
@A6GibKm It works!
