### ISSUE TITLE
Cant Launch After Last Update 6/Jul/2019

### ISSUE THREAD

**Issue by Saroufim** [flathub/net.lutris.Lutris#14]
Lutris doesn't launch anymore. It yields the following error:

bwrap: Can't mkdir /app/lib/i386-linux-gnu/GL: Read-only file system
error: ldconfig failed, exit status 256

**Comment by gasinvein** [comment]
Is the extension `org.freedesktop.Platform.Compat.i386//19.08beta` installed?

**Comment by Saroufim** [comment]
That was indeed the issue. Shouldn't dependencies be pulled automatically after an update though?

**Comment by gasinvein** [comment]
That extension should be installed automatically during update. I'n not sure why it wasn't.

**Comment by gasinvein** [comment]
@Saroufim Flatpak guys in IRC told me that it may be gnome-software issue. What are your gnome-software and flatpak versions?

**Comment by Saroufim** [comment]
Gnome-software: 3.32.3-1.fc30
Flatpak: 1.4.2-1.fc30
OS: Fedora Silverblue 30

Would you like me to report this as a bug against gnome-software?

**Comment by gasinvein** [comment]
As far as I understood, it is a known bug of gnome-software.
