### ISSUE TITLE
wow64 in flatpak

### ISSUE THREAD

**Issue by fastrizwaan** [flathub/net.lutris.Lutris#143]
hi,

I think I've built wine with wow64 support in flatpak sandbox. https://github.com/fastrizwaan/flatpak-wine/blob/main/wine-x86_64/io.github.wine-x86_64.yml

Thanks.

**Comment by gasinvein** [comment]
I'm not sure what it has to do with Lutris and why you're posting it here.

**Comment by fastrizwaan** [comment]
lutris does not compile wine, so it can compile wine with flatpak-builder that's why.

**Comment by gasinvein** [comment]
Lutris flatpak used to have a [Wine extension](https://github.com/flathub/net.lutris.Lutris.Runner.Wine), it was just left unmaintained now.

**Comment by fastrizwaan** [comment]
Thanks!
