### ISSUE TITLE
Cannot get Java to work

### ISSUE THREAD

**Issue by tommytran732** [flathub/net.lutris.Lutris#147]
Hi,

I cannot seem how to get Java to work with Lutris Flatpak. I am trying to install Minecraft (yes, I know the standalone Flatpak Minecraft package exist), and it is asking for Java to be installed.

![image](https://user-images.githubusercontent.com/57488583/113643463-602c5400-9650-11eb-9787-3e0822fc47e9.png)

I have tried installing org.freedesktop.Sdk.Extension.openjdk and set the environment variable FLATPAK_ENABLE_SDK_EXT=openjdk, yet the issue still persists. 

I hope you could help me figure out how to get Lutris working with Java

**Comment by nickavem** [comment]
I'm not certain if you can use Java without it being built into the application. I'd somewhat like to run my mod manager in lutris as well, so I'll try a build with java and maybe submit a PR as well depending on how it looks.

**Comment by nickavem** [comment]
SIgh, fair enough.
I'll give ATLauncher another shot, or maybe try something else.

**Comment by strycore** [comment]
Java and Mono need to be added to the Flatpak

**Comment by A6GibKm** [comment]
The PR above fixes the issue, but there is still a papercut. For some reason after installing the game, running it will fail with message "No executable found", after setting it manually it works.
