### ISSUE TITLE
Build Lutris for ARM and aarch64

### ISSUE THREAD

**Issue by LeandroStanger** [flathub/net.lutris.Lutris#15]

**Comment by gasinvein** [comment]
You mean build Lutris for ARM? That is something I'd like to do, it's going to be super complex. I'll look into it once #13 is finished.

**Comment by LeandroStanger** [comment]
i386 is still needed?

**Comment by gasinvein** [comment]
I hope not.

**Comment by strycore** [comment]
Right now we don't ship ARM runners, the client can be launched on ARM but we don't provide anything to run games with.
This means it would result in an horrible experience with Flatpak because of the sandboxing.
This issue should be closed and not reopened until we have proper ARM support.
