### ISSUE TITLE
libXmu missing

### ISSUE THREAD

**Issue by FakeShemp** [flathub/net.lutris.Lutris#152]
Recently I started getting a message of `ImportError: libXmu.so.6: cannot open shared object file: No such file or directory` on some games. I cannot remember this being an issue before. Has this library been removed from the runtime or app?

**Comment by A6GibKm** [comment]
It has not been removed from the app at least. I dont know if it was ever bundled in the runtime either.

**Comment by A6GibKm** [comment]
Could you please document which games did not work for you?

**Comment by FakeShemp** [comment]
https://lutris.net/games/doki-doki-literature-club/ is a free one, easy to test. 

However, testing it more it seems it only happens when Nvidia Optimus is used, so this might be a problem outside of Lutris.

**Comment by A6GibKm** [comment]
Is Nvidia optimus commonly used? if this issue appears whenever it is used we should bundle this in the app.

**Comment by FakeShemp** [comment]
I will look into this. I'm not sure why this suddenly started failing and only on some hardware, so I will investigate in more detail.

**Comment by FakeShemp** [comment]
Looking at the recommended packages for running Lutris, `x11-xserver-utils` is one of the included, which in turn is dependent on `libxmu`. So in the end I guess it would be a good idea to include in the manifest.
