### ISSUE TITLE
Retroarch no longer works

### ISSUE THREAD

**Issue by tommytran732** [flathub/net.lutris.Lutris#157]
**Describe the problem**
Retroarch no longer opens. I tried it a few months ago and it worked fine, but now it doesn't. Reproducible on both Silverblue and Arch.

**Is it reproducible with native Lutris?**
No

**Steps to reproduce**
1. Install the retroarch runner
2. Click on the "play" button on the retroarch runner

**Expected behavior**
Retroarch opens.

**Actual behavior**
Retroarch no longer opens.

**Flatpak info**
`flatpak --version`
Flatpak 1.11.2
`flatpak --gl-drivers`
nvidia-465-31
default
host

**Comment by junglized** [comment]
Can you start Lutris with `lutris -d`?

**Comment by junglized** [comment]
Maybe you have libraries required to run Retroarch missing. Never used Arch, but I had the same issue on Pop!_OS. Try to launch lutris from terminal `lutris -d` and then, with terminal still opened, try to launch Retroacrh configuration and see what debugging information in the terminal says.

**Comment by A6GibKm** [comment]
I cannot reproduce this issue, do you have `org.gnome.Platform.Compat.i386//40` installed?

**Comment by strycore** [comment]
Retroarch works on SteamOS
