### ISSUE TITLE
Is this normal behavior?

### ISSUE THREAD

**Issue by rowbawts** [flathub/net.lutris.Lutris#158]
When I launch Lutris it gives me a popup mentioning I dont't have 32 bit Vulkan support is that supposed to happen? Or am I missing an extension?

![Screenshot from 2021-07-16 13-29-54](https://user-images.githubusercontent.com/13012832/125986570-143e3359-56f0-43f2-803b-b53dcc131bd1.png)

![Screenshot from 2021-07-16 13-30-53](https://user-images.githubusercontent.com/13012832/125986666-fb6655de-d1b3-4164-8f39-8cc7114d332c.png)

**Comment by A6GibKm** [comment]
As per the README
```
flatpak install --user flathub org.gnome.Platform.Compat.i386 org.freedesktop.Platform.GL32.default org.freedesktop.Platform.GL.default
```

**Comment by rowbawts** [comment]
> As per the README
> 
> ```
> flatpak install --user flathub org.gnome.Platform.Compat.i386 org.freedesktop.Platform.GL32.default org.freedesktop.Platform.GL.default
> ```

Wow I'm an idiot I've installed this Flatpak before and just recently reinstalled my OS and was going through it again and rushed through and missed that part of the readme thinking I remembered how I'd done it before sorry but thanks!
