### ISSUE TITLE
Additional dependencies like convmv

### ISSUE THREAD

**Issue by juligreen** [flathub/net.lutris.Lutris#162]
I'm trying to write an installer for [this game's demo](https://lutris.net/games/touhou-06-embodiment-of-scarlet-devil/) and I require the the command line program "convmv" to convert the filenames to utf-8.

What would be the correct course of action to get this to run in this flatpak?
Would I download perl and convmv inside my installer?
Alternatively I could create a pull request to include convmv inside this flatpak.

**Comment by juligreen** [comment]
Thanks for the answer, I have indeed managed to download a portable version of perl and convmv.

https://github.com/flathub/net.lutris.Lutris/issues/136 also describes the need of a perl installation for winetricks, if it get's implemented it would make my installs easier as well.

**Comment by A6GibKm** [comment]
Having winetricks does justify perl. If indeed winetricks/protontricks cannot be run without it I would happily accept a PR for it.
