### ISSUE TITLE
Lutris seems to be creating folders in the wrong location.

### ISSUE THREAD

**Issue by rowbawts** [flathub/net.lutris.Lutris#167]
So when I install games with Lutris these folders keep getting recreated (User home folders in Documents) (I'm 90% sure Lutris is responsible for this)
![Screenshot from 2021-08-16 23-26-59](https://user-images.githubusercontent.com/13012832/129659101-88fe6101-0c8d-4177-a8c2-457284107aa3.png)

**Comment by juligreen** [comment]
This will happen with every flatpak application as they use the xdg-directories to interact with files on you host system.
Read this on how to change the location of the folders: https://wiki.archlinux.org/title/XDG_user_directories

**Comment by A6GibKm** [comment]
> This will happen with any flatpak application as they use the xdg-directories to interact with files on you host system.
> Read this on how to change the location of the folders: https://wiki.archlinux.org/title/XDG_user_directories

This will happen with any environment or software that respects XDG directories, this is wider than flatpak or GNOME.

**Comment by rowbawts** [comment]
I understand that much but what I'm saying is it's created them under ~/Documents rather than ~. Is that also intended behavior?
![Screenshot from 2021-08-17 11-10-07](https://user-images.githubusercontent.com/13012832/129752122-e09349fc-ad8a-42f8-841e-660cc412076e.png)

**Comment by A6GibKm** [comment]
> I understand that much but what I'm saying is it's created them under ~/Documents rather than ~. Is that also intended behavior?

Certainly not, I cannot reproduce it either.

**Comment by rowbawts** [comment]
Here I made a video on how I am able to reproduce it, it occurs with any installation of software that uses the Wine runner.

https://user-images.githubusercontent.com/13012832/129779405-cd7e2a1e-e48f-464f-bcc2-e8819271241f.mp4
