### ISSUE TITLE
libjpeg.so.8 is missing

### ISSUE THREAD

**Issue by Zenek963** [flathub/net.lutris.Lutris#177]
scummvm (Beneath a Steel Sky - GOG - ScummVM) won't work with error

`home/adam/.var/app/net.lutris.Lutris/data/lutris/runners/scummvm/bin/scummvm: error while loading shared libraries: libjpeg.so.8: cannot open shared object file: No such file or directory`

there is same error with libjpeg.so.8 on some wine apps
(gothic/ gothic 2 GOG installer)
`0100:err:wincodecs:jpeg_decoder_create Failed reading JPEG because unable to find libjpeg.so.8`

`flatpak --version`
Flatpak 1.11.3

`flatpak --gl-drivers`
nvidia-470-74
default
host

**Comment by Zenek963** [comment]
Bottles have same issue https://github.com/bottlesdevs/Bottles/issues/539

**Comment by Unrud** [comment]
**libjpeg** is build without backwards-compatibility with v8. It can be enabled with `-DWITH_JPEG8:BOOL=YES`. This can either be done in the [runtime](https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/blob/master/elements/components/jpeg.bst#L11) or here by shipping own version of libjpeg.

**Comment by jbbandos** [comment]
Installing libjpeg.so.8 from debian snapshots doesn't fix the issue, as it will now fail when loading scummvm:
![image](https://user-images.githubusercontent.com/13665957/151118911-a9a07643-169a-4981-ab7e-43050d211f1f.png)
