### ISSUE TITLE
League of Legends installer - missing zenity

### ISSUE THREAD

**Issue by UsernameRandomlyGenerated** [flathub/net.lutris.Lutris#182]
**Describe the problem**
While trying to install League of Legends using standard installe from Lutris site, it shows "The installer requires zenity on your system" error and can't proceed. Installing zenity as a standard package results in the same error.

**Is it reproducible with native Lutris?**
No.
**Steps to reproduce**
1. Install Lutris according to instructions in github main page
2. Try to install League of Legends from Lutris site

**Expected behavior**
Installer works, gets on with installation.

**Actual behavior**
Installer complains about zenity not installed and then it's blank, can't proceed with installation.

**Flatpak info**
`flatpak --version`
Flatpak 1.10.3
`flatpak --gl-drivers`
default
host

**Comment by anthonytzvetkov** [comment]
PLEASE FIX I CAN'T PLAY LOL LINUX MINT

**Comment by A6GibKm** [comment]
This [project](https://github.com/flathub/io.github.divverent.aaaaxy/blob/655335666967588668cb0963841f2aac20715591/io.github.divverent.aaaaxy.yml#L165) bundles zenity, I suggest you to try bundling it an make a PR, the truth is that I cannot test such a PR as I dont have a LoL account but if you provide it some testing is done ill be happy to include it.

**Comment by juligreen** [comment]
I might try to do this if I have some time this weekend

**Comment by A6GibKm** [comment]
!199 includes zenity can anyone test it?

**Comment by ppGodel** [comment]
i can confirm is not working

DEBUG    2022-01-07 21:24:13,818 [http.get:81]:GET https://lutris.net/api/installers/league-of-legends
DEBUG    2022-01-07 21:24:14,201 [application.show_window:259]:Showing window <class 'lutris.gui.installerwindow.InstallerWindow'>league-of-legends
DEBUG    2022-01-07 21:24:15,743 [displayconfig.get_current_resolution:624]:Retrieving current resolution
ERROR    2022-01-07 21:24:15,744 [errors.__init__:18]:This installer requires zenity on your system

**Comment by ppGodel** [comment]
@A6GibKm the library is needed at game instalation, you dont need a lol account to test it.

**Comment by ppGodel** [comment]
i tried to build the flatpak but it throw me this error:

> $ flatpak remote-add --user flathub-beta https://flathub.org/beta-repo/flathub-beta.flatpakrepo
flatpak update --appstream
error: Remote flathub-beta already exists
Updating appstream data for remote fedora
Updating appstream data for remote flathub
Updating appstream data for user remote flathub-beta
$ flatpak-builder --repo=lutris --force-clean --install-deps-from=flathub-beta  --user build-dir net.lutris.Lutris.yml
Dependency Sdk: org.gnome.Sdk 41
Installing org.gnome.Sdk/x86_64/41 from flathub-beta
error: Nothing matches org.gnome.Sdk in remote flathub-beta
Error installing deps: running `flatpak --user install -y --noninteractive flathub-beta org.gnome.Sdk/x86_64/41`: Child process exited with code 1

**Comment by TheNamelessWonderer** [comment]
Is the lutris package in the beta repo not being updated with new builds?

**Comment by A6GibKm** [comment]
> flatpak-builder --repo=lutris --force-clean --install-deps-from=flathub-beta --user build-dir net.lutris.Lutris.yml

You are going to run into trouble if you ask your deps to come from flathub-beta.

**Comment by A6GibKm** [comment]
> Is the lutris package in the beta repo not being updated with new builds?

It is updated regularly.

**Comment by A6GibKm** [comment]
I am getting
```
/usr/lib/python3.9/site-packages/gi/overrides/GObject.py:493: Warning: ../gobject/gsignal.c:2731: instance '0x5654de67ca40' has no handler with id '40328'
  return func(*args, **kwargs)
```
there is a signal thats being disconnected and does not exist...

**Comment by UsernameRandomlyGenerated** [comment]
So I guess I should close the issue now? Installer works fine (for me at least), though you still need to compile flatpak yourself and remove modify_ldt sandbox option so you can actually play the game.

**Comment by strycore** [comment]
Yes, it seems the zenity specific issue is solved
