### ISSUE TITLE
Missing shared library libQt5Xml.so.5

### ISSUE THREAD

**Issue by motorto** [flathub/net.lutris.Lutris#187]
**Describe the problem**
Missing shared library libQt5Xml.so.5:

**Steps to reproduce**
1. Try to install MultiMC 
2. Run it

**Actual behavior**
It complains about libQt5Xml.so.5 missing.

**Flatpak info**
```
$ flatpak --version 
Flatpak 1.10.3

$ flatpak --gl-drivers 
nvidia-470-74
default
host
```

Here is the Game log:
```
Running /var/home/cerqueira/Games/multimc/MultiMC
Initial process has started with pid 42
Start monitoring process.
MultiMC Dir: /run/media/hdd/Games/multimc
No missing dependencies found.
/run/media/hdd/Games/multimc/MultiMC: error while loading shared libraries: libQt5Xml.so.5: cannot open shared object file: No such file or directory
Monitored process exited.
Initial process has exited (return code: 32512)
All children have exited.
Exit with returncode 32512
```

**Comment by CharoSW** [comment]
While it'd be possible to bundle the QT libraries here it would probably make more sense to raise this up to main Lutris devs for inclusion in their Runtime.  There are a lot of them and to start including one may pull in a lot of others or create precedent to bundle a lot of other libraries which would balloon the size of the flatpak

**Comment by strycore** [comment]
>  would balloon the size of the flatpak

We don't care about the size of the flatpak.

**Comment by A6GibKm** [comment]
A better solution would be to create an extension or something of the sort for those beefy modules, but for the moment I guess we will add everything

**Comment by strycore** [comment]
Yes, we can always slim down the flatpak later. Right now the goal is to reach maximum compatibility with games.

**Comment by strycore** [comment]
Qt5 is now included in the Flatpak

**Comment by omichalek** [comment]
I am still getting this error
`error while loading shared libraries: libQt5Xml.so.5: cannot open shared object file: No such file or directory`
running 0.5.11 (flatpak)
Do I need to enable anything anywhere please?
