### ISSUE TITLE
Wine is not installed on your system

### ISSUE THREAD

**Issue by alvarlagerlof** [flathub/net.lutris.Lutris#191]
I get this error every time, unless I click it away. I guess it's looking for wine in the normal paths? To be clear it doesn't seem to matter because it works anyway.

**Comment by juandpineiro** [comment]
In my case, I'm trying to install a Linux game from GOG (Hollow Knight) and after downloading the installer it says that Wine is not installed `Runtime Error Wine is not installed` (which it is, and anyways why should it matter if it's a Linux game?). The installer cancels and so the game is not installed.

**Comment by A6GibKm** [comment]
Yes, we bundle a wine version on the flatpak, but it is also possible to use the ones packaged by lutris itself. @alvarlagerlof , @juandpineiro  could you confirm if this is still an issue?

**Comment by A6GibKm** [comment]
We use the Wine extension, which I think includes 32bit wine, cc @gasinvein .

just to be sure, do you have `org.winehq.Wine` and `org.gnome.Platform.Compat.i386` (the 42 branch) installed?

**Comment by strycore** [comment]
Not sure, I tried installing Lutris from Discover on the Deck and did not install anything else. So I guess not?

**Comment by A6GibKm** [comment]
please run `flatpak list |grep org.gnome.Platform.Compat.i386`, and ditto for the other.

**Comment by alvarlagerlof** [comment]
> Yes, we bundle a wine version on the flatpak, but it is also possible to use the ones packaged by lutris itself. @alvarlagerlof , @juandpineiro could you confirm if this is still an issue?

Works for me now

**Comment by strycore** [comment]
> please run flatpak list |grep org.gnome.Platform.Compat.i386, and ditto for the other.

I just reinstalled the Flatpak on the Deck and I don't have it installed. I get this message when opening Lutris: 

`flatpak install --user flathub org.gnome.Platform.Compat.i386//42`

But the command doesn't work:

`error: No remote refs found similar to ‘flathub’`

**Comment by A6GibKm** [comment]
I have to wonder how did that happen... thanks Valve for putting us all in this situation :sweat:.

 ```
 flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
 ```

**Comment by strycore** [comment]
The command `flatpak install org.gnome.Platform.Compat.i386 ` worked, I just had to select flathub and runtime 42 manually. 
Both Flathub and Flathub Beta are present by default on the Deck

**Comment by strycore** [comment]
Even after running the `remote-add` command, I get the same error

**Comment by A6GibKm** [comment]
org.gnome.Platform.Compat.i386 cannot be installed manually because it is in `flathub` (in contrast to `flathub-beta`) and flatpak does not allow extensions to be automatically installed between different repositories.

I added a dialog at script to check this at launch and throw a nice warning if it is missing and how to install it.

**Comment by strycore** [comment]
I understand, but the commands given to install the dependencies (including GL and GL32) don't work for some reason when given the --user flathub flags but run ok without

**Comment by A6GibKm** [comment]
I just found out that `--user` only works if you also have the repo installed as user (which in this case it is installed system wide)

**Comment by VihagChaturvedi** [comment]
> Yes, we bundle a wine version on the flatpak, but it is also possible to use the ones packaged by lutris itself. @alvarlagerlof , @juandpineiro could you confirm if this is still an issue?

@A6GibKm I remember looking into a project called "Winepak" a while back for trying to run a game as a flatpak

The project was abandoned the last time i saw it, maybe that can be re-used?

**Comment by gasinvein** [comment]
The Lutris flatpak app bases on the Wine flatpak since #212, so `wine`/`wine64` binaries should be available for Lutris.

**Comment by VihagChaturvedi** [comment]
> The Lutris flatpak app bases on the Wine flatpak since #212, so `wine`/`wine64` binaries should be available for Lutris.

Sure, but from what it seems like, the binaries seem dated

It would be nice if there was a Wine SDK which is actively maintained, in addition to what we have on Lutris, similar to the model followed by the native Lutris builds

Or, manually update Wine everytime in Lutris a new update is pushed.

Hence why I i brought up Winepak, as it does seem to have SDKs (not sure of the quality) and seemingly a dead project

Proton does seem to have figured out Flatpak Wine, although I am nowhere educated enough to bring up that point and how they figured it out

**Comment by A6GibKm** [comment]
If you think that wine release is too old, you can use the one bundled by lutris or add a custom one.

**Comment by VihagChaturvedi** [comment]
> If that wine release is too old for your usecase, you can use the one bundled by lutris or any custom one.

Sorry if i was not clear enough, but I am implying that the Wine version currently bundled in the lutris flatpak is the that is old

I will see what I can try and do. Thanks

**Comment by A6GibKm** [comment]
If lutris bundles an old release that should be reported at lutris/lutris.

**Comment by gasinvein** [comment]
The issue title is "Wine is not installed on your system". Please, lets stay on topic. If it's detected but is too old for you case, or you want a different wine flavour - you can open a different issue.

**Comment by A6GibKm** [comment]
Following https://github.com/flathub/net.lutris.Lutris/issues/191#issuecomment-1087955099 I am closing this. It should have been fixed with the `home` access.

Please feel free to reopen if the issue persists.
