### ISSUE TITLE
Create a Wiki

### ISSUE THREAD

**Issue by LeandroStanger** [flathub/net.lutris.Lutris#2]

**Comment by gasinvein** [comment]
@nedrichards Can you please enable wiki for this repository?

**Comment by nedrichards** [comment]
We normally really don't. Flathub is not intended to be a project where software is developed - that is supposed to happen inside upstream. Happy to have a wider discussion about it if you have specific needs though.

**Comment by gasinvein** [comment]
I just want to remove the build/install instructions from the readme.md, so documentation can be edited without pushing negligible commits to the repo. And the dosc are needed, well, because this is still work-in-progress and we want to help users to test or collaborate.
Wikis are not uncommon among Flathub apps repos, though, e.g. Steam and Discord have ones.

**Comment by RobLoach** [comment]
@gasinvein We could host the Flatpak documentation over at the Lutris wiki:
https://github.com/lutris/lutris/wiki

Just have a link to it in the README.md.

**Comment by nickavem** [comment]
I've noticed this at Lutris/docs and thought about writing a couple simple things (like wine install etc.). Does this project have nay upstream support whatsoever? A feature on lutris.net (with the beta status obviously indicated) could make this package a little more discoverable outside a relatively obscure branch of flathub, and immutable desktop users trying to play games (🙃).

**Comment by gasinvein** [comment]
@nickavem 
>Does this project have nay upstream support whatsoever?

No. And that's why I doubt it'll ever leave beta.

**Comment by nickavem** [comment]
Well that's disappointing. Do you think it would be worth a PR (even in just the docs?)

**Comment by strycore** [comment]
>  Does this project have nay upstream support whatsoever?

Yes.

**Comment by strycore** [comment]
Why would a wiki be needed??

**Comment by A6GibKm** [comment]
> Why would a wiki be needed??

To explain how to install it, but all the non-trivial steps are directly related to the fact that we are in `flathub-beta`

I don't think we need a wiki, but there might be a case for a page in the lutris wiki if there are nontrivial workarounds that the user has to be aware of. I am closing as there is no point in having a wiki here. One example of why this might be useful is to suggest flatpak extensions that we might add in the future, but upstream can be modified to suggest them instead when the user requires them.

**Comment by RobLoach** [comment]
Thanks! Feel free to add anything you'd like to the README. It could always use some updates.
