### ISSUE TITLE
Add Gallium Nine Compatibility

### ISSUE THREAD

**Issue by Saroufim** [flathub/net.lutris.Lutris#20]
In order for Gallium Nine to work with Lutris, it needs to have access to /usr/lib/d3d which it currently doesn't have access to.

**Comment by gasinvein** [comment]
We can't pass-through anything under `/usr`, it's the mount point of flatpak runtime. You should probably ask [the runtime](https://gitlab.com/freedesktop-sdk/freedesktop-sdk) developers for Mesa Direct3D9 support.

**Comment by Saroufim** [comment]
Reported [here](https://gitlab.com/freedesktop-sdk/freedesktop-sdk/issues/825)

**Comment by gasinvein** [comment]
This should be fixed upstream now. If it won't start working after updates for both the runtime and wine-nine-standalone, feel free to reopen.

**Comment by Saroufim** [comment]
Just a general question, since wine-nine-standalone seems to be slow on updates, is there a workaround to this at the moment?

**Comment by gasinvein** [comment]
@Saroufim yes, `D3D_MODULE_PATH` env var.

**Comment by Saroufim** [comment]
`flatpak run --env=D3D_MODULE_PATH='/home/user/.local/share/flatpak/runtime/org.freedesktop.Platform.GL32.default/x86_64/19.08beta/783a914d6fbd30729255e5a854de221c9d9ba283e5a1e703aa7439e1e9fab752/files/lib/d3d' net.lutris.Lutris
bwrap: Can't mkdir /app/lib/i386-linux-gnu/GL: Read-only file system
error: ldconfig failed, exit status 256
`
What am I doing wrong?

**Comment by A6GibKm** [comment]
See #41

**Comment by gasinvein** [comment]
First, you should set any paths as they are seen from inside of the sandbox, i.e. `D3D_MODULE_PATH` should probably be set to `/usr/lib/x86_64-linux-gnu/GL/lib/d3d:/usr/lib/i386-linux-gnu/GL/lib/d3d`.
And second, the `.Compat.i386` extension is broken currently, sorry. Either install a test build from #41 or wait for the Gnome runtime to update.

**Comment by Saroufim** [comment]
Thank you very much for your feedback. I will wait for a GNOME update before trying again

**Comment by gasinvein** [comment]
@Saroufim If you have a pure-64bit game, you can try gallium-nine with it, it should work without `.Compat.i386` extension.

**Comment by Saroufim** [comment]
There's an issue with Gallium Nine. It seems that it is not connecting to the native libraries. Gallium Nine seems to be working and it reports that it is active but offers no performance benefits at all. Sometimes the performance is even worse. I've initially attributed this as a bug in Gallium Nine itself but now I'm starting to think otherwise as I've reset all layered packages installed in Fedora Silverblue and among them was mesa-libd3d.i686 which is supposedly needed for Gallium Nine to work yet Gallium Nine still reports that it is active despite the lack of this, supposedly necessary, library. Should I open a new bug report about this or is this someone else's bug?

**Comment by gasinvein** [comment]
wine-nine-standalone 0.5 released, should pick up libs from flatpak paths now https://github.com/flathub/com.valvesoftware.Steam/issues/410#issuecomment-535003914

**Comment by Saroufim** [comment]
I removed the environment variables I have previously set for Galliun Nine to detect the d3d libraries and upgraded to Galliun Nine 0.5. It didn't pick the libraries up and it's now greyed out.

**Comment by gasinvein** [comment]
@Saroufim does it work for 64-bit, e.g. `wine64 ninewinecfg`?

**Comment by Saroufim** [comment]
Yes. Through wine64 it works

**Comment by gasinvein** [comment]
Then it's our bug, likely due to missing `lib/d3d` in `merge-dirs`of the GL32 extension. Will push a fix.

**Comment by Saroufim** [comment]
I think this issue is once again relevant because Lutris's toggle to activate gallium nine is always greyed out whether or not libd3d is detected
