### ISSUE TITLE
Appimage games are missing fuse

### ISSUE THREAD

**Issue by MinmoTech** [flathub/net.lutris.Lutris#200]
**Describe the problem**
Appimage-installed games like [osu lazer](https://lutris.net/games/osu/) need fuse installed to launch.

**Is it reproducible with native Lutris?**
No

**Steps to reproduce**
1. Install `Osu!lazer version`
2. Try to launch

**Expected behavior**
Should start normally.

**Actual behavior**
Fails to start with error message: `fuse: failed to exec fusermount: No such file or directory`

**Flatpak info**
`flatpak --version`: `Flatpak 1.12.2`
`flatpak --gl-drivers`:
```
nvidia-495-46
default
host
```

**Comment by juligreen** [comment]
Possible example to implement:
https://github.com/flathub/com.borgbase.Vorta/blob/b324ae38ffdce051441fbb4b50274c764047f144/dependencies/libfuse.json

**Comment by A6GibKm** [comment]
Please open a PR, i dont have the means to test such thing.

**Comment by juligreen** [comment]
> Please open a PR, i dont have the means to test such thing.

Don't worry, I intend to :)
I just document my issues until I have time to try and fix it (or for someone else interested in fixing it) :v:

**Comment by Unrud** [comment]
AppImage programs have the command line option `--appimage-extract-and-run`. Which extracts the squashfs to `/tmp` instead of using **fuse**.

**Comment by MinmoTech** [comment]
Yes, that might be the best way to implement this, even with the solution in my PR applications were running very slow so I abandoned that approach.

**Comment by soredake** [comment]
Actually, appimages can be run in flatpak, they can be launched with [--appimage-extract-and-run](https://github.com/AppImage/AppImageKit/issues/841) argument and [NO_CLEANUP=1](https://github.com/AppImage/AppImageKit/pull/842/files#diff-50977a57b5cd77600b845d12867637b22f364a61b16a6d80791037caf018429fR665-R669) env to skip cleaning up files after each run.
