### ISSUE TITLE
Support for Gamemode

### ISSUE THREAD

**Issue by LeandroStanger** [flathub/net.lutris.Lutris#22]
https://github.com/FeralInteractive/gamemode

**Comment by gasinvein** [comment]
@nanonyme since there is a portal for GameMode, do we need anything special to support it?

**Comment by nanonyme** [comment]
Afaik no other than sufficiently new gamemode library.

**Comment by Bryophyllum** [comment]
It does not work for me. I'm on Fedora Silverblue 30, and despite having freedesktop-sdk _(for mesa-aco)_ and Lutris installed, the log is flooded with: 
`ERROR: ld.so: object '/usr/$LIB/libgamemodeauto.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.`

**Comment by gasinvein** [comment]
I wonder what's the reason for hardcoding full path instead of letting the linker find the library. In our case, it's under `/app`, not `/usr`. @Bryophyllum, probably you should report this upstream.

**Comment by Bryophyllum** [comment]
@gasinvein Correct me if I'm wrong, but isn't this a problem with how [Gamemode](https://github.com/flathub/com.valvesoftware.Steam/issues/393#issuecomment-515671692) works, by any chance? If so, I must close the above issue.

**Comment by gasinvein** [comment]
@Bryophyllum no, the problem is with how `libgamemodeauto.so` is loaded by Lutris. You can check if gamemode works like this:
```
flatpak run --command=env net.lutris.Lutris LD_PRELOAD=libgamemodeauto.so sleep 10
```
(replace `sleep 10` with anything you'd like, e.g. `lutris` itself)

**Comment by gasinvein** [comment]
Looks like the `gamemoderun` helper script [uses](https://github.com/FeralInteractive/gamemode/blob/4ecac891afe3f70c5a0329e53b2f6c48e398aec4/data/gamemoderun.in#L6) full path, too, but at least the prefix is determined at build time and not static.

**Comment by nanonyme** [comment]
Then again, gamemoderun detection is broken for Flatpak as we use it because $LIB gets expanded to i386-linux-gnu which is not the path we use for installing 32bit app libraries.

**Comment by nanonyme** [comment]
I think it would probably be cleanest if system_config could also set the gamemode library name, not just toggle it on and off. Then all you would need to do is figure out how to provide a system config that configures right name. The other option is patching which would be more of a hassle to maintain.

**Comment by gasinvein** [comment]
I don't understand why not just use library name without a path. `ld.so` handles it just fine.

**Comment by LeandroStanger** [comment]
- [ ] Build Gamemode as an extension for Lutris and Steam

**Comment by nanonyme** [comment]
Maybe they were trying to protect against games shipping their own gamemode libraries *shrug*

**Comment by A6GibKm** [comment]
It is possible to temperarily fix this by addying a `patches/game.py.patch` with contents
```diff
diff --git a/lutris/game.py b/lutris/game.py
--- a/lutris/game.py
+++ b/lutris/game.py
@@ -470,7 +470,7 @@
                     path
                     for path in [
                         env.get("LD_PRELOAD"),
-                        "/usr/$LIB/libgamemodeauto.so",
+                        "libgamemodeauto.so",
                     ]
                     if path
                 ]
```
while it is added upstreams? The error does not appear anymore but I am not sure if it is working properly as the only output I get is
```
$ flatpak run net.lutris.Lutris -d

Listing '/app/lib/debug/source/gamemode'...
Listing '/app/lib/debug/source/gamemode/_flatpak_build'...
Listing '/app/lib/debug/source/gamemode/lib'...
Listing '/app/lib/debug/source/gamemode-32bit'...
Listing '/app/lib/debug/source/gamemode-32bit/_flatpak_build'...
Listing '/app/lib/debug/source/gamemode-32bit/lib'
...gamemodeauto: 
```
