### ISSUE TITLE
Genshin Impact "Insufficient System Drive Space..." even though I have enough space available

### ISSUE THREAD

**Issue by VihagChaturvedi** [flathub/net.lutris.Lutris#223]
**Describe the problem**
Upon installing GI by creating a prefix and Running the Installer via "Run EXE Inside Prefix", the game refuses to install due to lack of storage

Ideally, the game requires ~40GB (Including some amt of overhead) of free storage to work. I currently happen to have 156GB free on my computer.

**Is it reproducible with native Lutris?**

No, the installation was smooth on Native Lutris.

**Steps to reproduce**
1. Create a new game by "Add a new game"
2. Create a new wine prefix by creating a new directory
3. Install and Run the GI Installer on the official website by executing "Run EXE Inside Wine prefix" on the newly created prefix
4. You are required a virtual desktop for the keyboard and mouse to function properly
4. Follow through the prompts on the installer

**Expected behavior**
Expected the installation to take place smoothly

**Actual behavior**
The Installer runs, but prompts that the space is insufficient

**Additional Info**
Here is the paste bin to what I noticed in the terminal (Although there is nothing particular that really stood out)

[The paste bin in question](https://pastebin.com/LsX84R7Q)

**Flatpak info**
`flatpak --version`
Flatpak 1.12.4

`flatpak --gl-drivers`
nvidia-510-47-03
default
host

To clarify, yes I do use Nvidia.

**Comment by A6GibKm** [comment]
This is the list of paths where the flatpak has access to
```
  - --filesystem=~/Games:create
  - --filesystem=xdg-desktop
  - --filesystem=xdg-documents
  - --filesystem=xdg-pictures
  - --filesystem=xdg-music
  - --filesystem=xdg-videos
  - --filesystem=xdg-download
```

If you want more access you can a combination of these, `--filesystem=home`, `host` or `actual-path-you-need`. To use these permissions:

```
flatpak run --filesystem=... net.lutris.Lutris
``

you can also use `flatpak override --user` to permanently set them. I hope this helps.

**Comment by VihagChaturvedi** [comment]
Thank you for your response, @A6GibKm 

However, I have already set those permissions.

![image](https://user-images.githubusercontent.com/45941793/160239660-cbbfbd10-0bbf-4a79-8aa2-05ac204a2322.png)

![image](https://user-images.githubusercontent.com/45941793/160239683-746c0bcd-ebaf-4e6f-bc5a-800adf58a2bd.png)

Do note that it is normal to have the executable directory to be empty for this step

**Comment by VihagChaturvedi** [comment]
Here is a screenshot further supporting the issue.

Is this some sort of WINE config issue with the current Lutris Flatpak?

![image](https://user-images.githubusercontent.com/45941793/160287123-b335222b-f3d1-44ec-8cfb-3bb814e38c0f.png)

**Comment by A6GibKm** [comment]
There shouldn't be an issue, but note that it all depends on how the app measures free disk space, thats in general not a sandbox friendly operation.

**Comment by VihagChaturvedi** [comment]
> There shouldn't be an issue, but note that it all depends on how the app measures free disk space, thats in general not a sandbox friendly operation.

I mean, it clearly did work with Native Lutris.

What are your thoughts to what the issue can be? Maybe the Installer isn't able to access the directory? In that case, it would make sense that the installation is failing.

I have given Lutris access to the prefix, but to no avail.

**Comment by strycore** [comment]
Lutris flatpak currently has access to a bunch of folder it doesn't need but doesn't have access to the folder it should have access to. 

The best option is to give access to you full filesystem. This is likely what we'll end up doing because I don't see another way of having Lutris work properly otherwise.

**Comment by A6GibKm** [comment]
@VihagChaturvedi Could you please try running `flatpak run --fillesystem=host net.lutris.Lutris` and test this?

If that does not help, it might not be that it is missing access to a particular file/folder.

By the way I gave the flatpak access to the UDisks2 dbus interface a few days ago, this was used by wine to do disk related stuff, maybe that helps?

**Comment by VihagChaturvedi** [comment]
> @VihagChaturvedi Could you please try running `flatpak run --fillesystem=host net.lutris.Lutris` and test this?
> 
> If that does not help, it might not be that it is missing access to a particular file/folder.
> 
> By the way I gave the flatpak access to the UDisks2 dbus interface a few days ago, this was used by wine to do disk related stuff, maybe that helps?

Sorry for the late response

I have tested stuff out in the latest release, seems to work just fine

I have switched to a new distro during this time (From Ultramarine Linux (Fedora based) --> Fedora Silverblue)

Installation seems to work properly. Thank you for your time
