### ISSUE TITLE
[Gnome] Wine runner overrides application title & icon (Lutris' shown instead)

### ISSUE THREAD

**Issue by Mershl** [flathub/net.lutris.Lutris#224]
Same runner and parameters used.

## Game started through Lutris rpm
![image](https://user-images.githubusercontent.com/520251/160260274-cfdd63a9-d417-4c04-9d9e-4feef45da072.png)
![image](https://user-images.githubusercontent.com/520251/160260313-2d349768-943c-4d05-ae50-93f5ad24d25d.png)

## Game started through Lutris flatpak
![image](https://user-images.githubusercontent.com/520251/160260226-142380a3-3980-47ac-bdca-137fdaeee1d7.png)
![image](https://user-images.githubusercontent.com/520251/160260332-e59b3589-24d6-4dc0-8b0f-ad57a3b9ad98.png)

**Comment by strycore** [comment]
This probably cannot be fixed to due the nature of Flatpak, you can close this issue,

**Comment by TingPing** [comment]
It depends on how the application sets its icon.

Icon set by data will work in a sandbox.

Icon set by icon-name will not work in a sandbox (unless you do hacky things).

Icon set by file path can work, as long as the icon is in a path readable by the host.
