### ISSUE TITLE
Missing libslang for Dosbox

### ISSUE THREAD

**Issue by strycore** [flathub/net.lutris.Lutris#234]
/home/strider/Games/gog/normality/dosbox/dosbox_x86_64: error while loading shared libraries: libslang.so.2: cannot open shared object file: No such file or directory

**Comment by A6GibKm** [comment]
Do you think that running https://github.com/dosbox-staging/dosbox-staging instead can work here?

**Comment by strycore** [comment]
Dosbox Staging is what we ship, it's what I was trying to run

**Comment by A6GibKm** [comment]
Could you try the build at https://github.com/flathub/net.lutris.Lutris/pull/236? (you can run different branches with `flatpak run net.lutris.Lutris//test`, the default being the `beta` branch)

I find weird that in that build I was able to build dosbox-stating and the only deps that were missing were munt and libslirp.

**Comment by A6GibKm** [comment]
slang is part of the runtime, I wonder if the issue here is that the shipper version requires an older version 

See https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/blob/master/elements/components/slang.bst.

**Comment by strycore** [comment]
This is fixed
