### ISSUE TITLE
Missing libopenal, no sound in Quake 3

### ISSUE THREAD

**Issue by strycore** [flathub/net.lutris.Lutris#239]
```------ Initializing Sound ------
Loading "libopenal.so.0"...
Failed to load library: "libopenal.so.0".
```

**Comment by A6GibKm** [comment]
openal is in the runtime, ill bundle the older so.0 version tomorrow

https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/blob/master/elements/components/openal.bst

**Comment by A6GibKm** [comment]
Note that I do have sound in Quake 3, maybe this is an issue with the steam version?

**Comment by strycore** [comment]
I have sound on the Deck with Quake 3, and I'm playing the GOG version with ioquake3

**Comment by strycore** [comment]
Looks like I have sound on all devices now
