### ISSUE TITLE
OSError(16, 'Device or resource busy')

### ISSUE THREAD

**Issue by prozmoon** [flathub/net.lutris.Lutris#241]
After installing Epic Game Launcher and successfully installing and playing several games from it, I am no longer able to install anything without getting OSError16. Tried installing Origin, GOG, Mass Effect, Dead Space, Medal of Honor, etc... I am unable to find anything that will install.

I am able to reproduce this 100%. OS is Fedora Silverblue 35.

![Screenshot from 2022-04-05 23-22-22](https://user-images.githubusercontent.com/71403541/161895261-53a23fc9-c39f-48e8-aa27-dac56195a494.png)

**Comment by A6GibKm** [comment]
Can you please test with
```
flatpak run --filesystem=home net.lutris.Lutris
```

**Comment by prozmoon** [comment]
That worked. Interesting.

Thank you so much, good sir or mam.
