### ISSUE TITLE
West of Loathing from GOG fails to run once installed

### ISSUE THREAD

**Issue by kozross** [flathub/net.lutris.Lutris#248]
**Describe the problem**

After I connect my GOG account, I installed West of Loathing. However, when I try to run it, the game doesn't even start. The logs show this:

```
lutris-wrapper: West of Loathing
Started initial process 344 from /home/koz/Games/gog/west-of-loathing/start.sh
Start monitoring process.
Running West of Loathing
support/gog_com.shlib: line 106: ./West of Loathing.x86_64: Permission denied
Monitored process exited.
Initial process has exited (return code: 32256)
All processes have quit
Exit with return code 32256
```

**Is it reproducible with native Lutris?**

N/A I think?

**Steps to reproduce**
1. Open Lutris installed from Flatpak.
2. Connect GOG account.
3. Install West of Loathing.
4. Try to run it, and see that it doesn't work.
5. Check the logs.
6. Cry.

**Expected behavior**

West of Loathing should have started.

**Actual behavior**

West of Loathing does not run, giving instead the logs above.

**Flatpak info**
`flatpak --version` gives `Flatpak 1.12.7`
`flatpak --gl-drivers` gives 

```
default
host
```

**Comment by strycore** [comment]
I have at least one GOG native game running from the Flatpak without issues (Carrion).
This might be caused by a missing dependency, may have to get the game to check this out.

**Comment by kozross** [comment]
How would a missing dependency cause a permdenied error? A segfault maybe. I'll try a manual installation and see if this is an issue with the game installer, rather than Lutris.

**Comment by strycore** [comment]
if the file exists and is executable then the error is likely due to a missing peer dependency. 
I've seen this kind of stuff happen but on 32bit games. This is clearly 64bit given the filename so I'm not sure what's causing it.

**Comment by kozross** [comment]
Figured it out, and I was right, it has nothing to do with dependencies. GOG's installer is broken: it doesn't chmod the game binary, which means it fails to execute via the `start.sh` wrapper script. I can close this issue, since it's a problem with GOG's so-called 'Linux support', rather than Lutris itself.
