### ISSUE TITLE
Ship Flatpak with Steam shortcut patch

### ISSUE THREAD

**Issue by strycore** [flathub/net.lutris.Lutris#249]
I've added a patch to add support for the Steam shortcuts from Flatpak Lutris.

Since there are probably many patches to come before we can stabilize the Flatpak, I'd like to know the procedure for shipping an out of release commit.

Is it enough to replace the lutris archive with this link: 
https://github.com/lutris/lutris/archive/c8fef40b4f33d2a74b04577a970675b76129d702.zip
and update the checksum accordingly?

**Comment by A6GibKm** [comment]
Yes, thats an option. 👌

Another way is using type=git  url=repo_url and the desired commit.

**Comment by strycore** [comment]
The Flatpak is now using a recent commit
