### ISSUE TITLE
Libretro Runner Does Not Detect Gamepad

### ISSUE THREAD

**Issue by Saroufim** [flathub/net.lutris.Lutris#26]
The libretro runner does not detect the DualShock 4 gamepad input at all. 

**Is it reproducible with native Lutris?* No

**Steps to reproduce**
1. Connect the controller
2. Try any libretro core

**Expected behavior**
Libretro to detect the controller

**Flatpak info**
Flatpak 1.4.2

Extra info: Wine detects the controller just fine

**Comment by gasinvein** [comment]
Is the issue only with DS 4 or with any controller?

**Comment by Saroufim** [comment]
Dualshock 4 controllers are the only ones I have so I'm unable to answer that. Hopefully another user can.

**Comment by gasinvein** [comment]
@RobLoach is more familiar with RetroArch, maybe he has any ideas.

**Comment by Saroufim** [comment]
Everything works just fine with the RetroArch flatpak btw

**Comment by RobLoach** [comment]
What input driver are you using in the Lutris one? Can find it in settings, drivers.

**Comment by Saroufim** [comment]
It was x. I set it to udev and restarted RetroArch (the one in Lutris) and now not even the keyboard input works. I deleted the config then proceeded to try linuxraw. With the latter, the keyboard input worked but the controller didn't.

**Comment by RobLoach** [comment]
SDL might be an option if neither of those worked.

**Comment by Saroufim** [comment]
SDL is not available as an input driver, unfortunately.

**Comment by gasinvein** [comment]
And what input drivers do work in RetroArch flatpak?

**Comment by Saroufim** [comment]
Udev, x, and linuxraw

**Comment by RobLoach** [comment]
I've seen a changed to `--share=all`, but I think that might be overkill.

**Comment by soredake** [comment]
https://github.com/flathub/org.libretro.RetroArch/issues/153

**Comment by strycore** [comment]
Joypad is detected as expected.

**Comment by A6GibKm** [comment]
@strycore did you check both steam deck and Pop os?

**Comment by RobLoach** [comment]
I think we can close this. While SDL2 isn't the optimal input joypad driver, it does get around the udev permissions issue https://github.com/flathub/org.libretro.RetroArch/issues/194 .

**Comment by RobLoach** [comment]
@A6GibKm For SteamDeck or Pop OS, if you find it missing configs, feel free to submit over at https://github.com/libretro/retroarch-joypad-autoconfig .
