### ISSUE TITLE
Installer cannot find libbz2.so.1.0 on Steam Deck installation

### ISSUE THREAD

**Issue by IcingDeath** [flathub/net.lutris.Lutris#262]
**Descripe the problem**
I Installed the updated Lutris Flatpak (Version 0.5.10.1) on my Steam Deck.
Tried to install the GOG Windows version of Duke Nukem (the Linux version doesn't work for me either, but that's another topic)
and the Installer fails with return code 32512

**Is it reproducible with native Lutris**
Don't think so, the day before I installed the older Lutris version through pakman and could successfully install the game

**Steps to reproduce**

1. Log into GOG in Lutris Flatpak
2. Select Duke Nukem -> Install
3. Select the Windows version of Duke Nukem (not the Linux one)
4. keep the default setting with each following step
5. start the installation

**Expected Behavior**
Game gets installed, no error

**Actual Behavior**
Installer fails, Log content below:

```
lutris-wrapper: /home/deck/.var/app/net.lutris.Lutris/cache/lutris/installer/duke-nukem/unzip
Started initial process 87 from /home/deck/.var/app/net.lutris.Lutris/cache/lutris/installer/duke-nukem/unzip /home/deck/.var/app/net.lutris.Lutris/cache/lutris/installer/duke-nukem/gog/setup_duke_nukem_1.0_(28044).exe -d /home/deck/Games/gog/duke-nukem
Start monitoring process.
/home/deck/.var/app/net.lutris.Lutris/cache/lutris/installer/duke-nukem/unzip: error while loading shared libraries: libbz2.so.1.0: cannot open shared object file: No such file or directory
Monitored process exited.
Initial process has exited (return code: 32512)
All processes have quit
Exit with return code 32512
```

**Flatpak Info**
Flatpak 1.12.4
Flatpak GL-Drivers: 
```
default 
host
```

**Comment by strycore** [comment]
This is caused by the fact that the installer uses unzip (it shouldn't but that's another issue). 
gzdoom also requires this library so we should provide it in the Flatpak

**Comment by IcingDeath** [comment]
you're right, using unzip there seems to be a mistake, with the recent update the log shows the error that the package isn't a zip, but the libbz2 error seems to be fixed with the update

**Comment by strycore** [comment]
This fixed the problem for gzdoom as well (now it's missing another library)
