### ISSUE TITLE
Wine runner shows "could not find a wine-mono package" on prefix upgrade

### ISSUE THREAD

**Issue by Mershl** [flathub/net.lutris.Lutris#268]
**Describe the problem**
Wine runner shows a "Wine could not find a wine-mono package" warning on prefix upgrade.

The manifest states `inherit-extensions: org.winehq.Wine.mono` (maybe unrelated).

Is it necessary to manually install an additional extension? What's the recommended way to install the `wine-mono` package for Flatpak Lutris?

![image](https://user-images.githubusercontent.com/520251/167668482-6ac3e592-7309-4197-927b-cd590ed2e5b8.png)

**Comment by Mershl** [comment]
The note was what got me confused `is is recommended to use your distribution's packages instead`.

**Comment by strycore** [comment]
That's not possible with Flatpak
