### ISSUE TITLE
Add "7z" binary

### ISSUE THREAD

**Issue by AsciiWolf** [flathub/net.lutris.Lutris#275]
Please, consider adding the [p7zip](http://p7zip.sourceforge.net) module (containing "7z" binary) to Lutris modules. Some installers use the "7z" command.

Example of such installer is the RVGL installer from here: https://lutris.net/games/re-volt/

**Comment by strycore** [comment]
installers shouldn't use 7z directly, we ship 7z and it's accessible through the extract command. Installers that call 7z directly should be considered broken.

**Comment by AsciiWolf** [comment]
Ah, did not know this! Thanks for the info. :-)
