### ISSUE TITLE
Add Cabextract for Winetricks

### ISSUE THREAD

**Issue by Saroufim** [flathub/net.lutris.Lutris#28]
Winetricks complains about missing cabextract when attempting to install certain Windows DLLs such as DirectX9

**Comment by gasinvein** [comment]
Cabextract is present and workling
https://github.com/flathub/net.lutris.Lutris/blob/911cbd402e3ce2b15b4afec61b39d0af5c5b024b/net.lutris.Lutris.yml#L609-L613

How do you invoke winetricks?

**Comment by Saroufim** [comment]
Right click on a game then select winetricks. Admittedly, it only fails to install components sometimes. The bug is unreliable and does not happen all the times.

**Comment by gasinvein** [comment]
Closing now. If you find a reliable way to reproduce it, please reopen.
