### ISSUE TITLE
required-binaries: in installers are never found

### ISSUE THREAD

**Issue by NicBOMB** [flathub/net.lutris.Lutris#283]
**Describe the problem**
I wrote an installer for Vortex Mod Manager and specified exactly the `required-binaries:` used in my shell scripts as requirements. It was Steam Deck users following the [flatpak install instructions](https://lutris.net/downloads) who reported that an error appears when using my installer. I installed Lutris 5.11 from the flathub-beta and encountered the same issue they reported to me here: https://github.com/Nexus-Mods/Vortex/issues/10686#issuecomment-1207448890

**Is it reproducible with native Lutris?**
No. On Manjaro running native Lutris, I do not encounter this issue. 

**Steps to reproduce**
1. Install Lutris using either the [flatpak install instructions for Steam Deck](https://lutris.net/downloads) or [flathub-beta install instructions](https://github.com/flathub/net.lutris.Lutris#installation).
2. 
```
❯ flatpak run net.lutris.Lutris "lutris:vortex-mod-manager?revision=90249"
Failed to load module "xapp-gtk3-module"
Failed to load module "canberra-gtk-module"
Starting Lutris 0.5.11
Using NVIDIA drivers 515.65.01 for x86_64
GPU: NVIDIA GeForce GTX 1080 Ti
GPU: 10DE:1B06 3842:6694 (nvidia drivers)
This installer requires steam on your system
None
```
3. ![This installer requires steam on your system](https://user-images.githubusercontent.com/19939315/183313209-baf12a00-c28a-49af-8e7c-ed94be904769.png)

**Expected behavior**
The installer would find the `required-binaries:`.

**Actual behavior**
The installer pops an error on any of the `required-binaries:` saying `None` even if the requirement is _definitely_ installed.

**Comment by strycore** [comment]
This is a limitation of Flatpak and cannot be solved

**Comment by strycore** [comment]
We do have other ways of detecting Steam in the Flatpak but it won't matter for the require-binary rule. 
The installer should be modified so this requirement is removed.
