### ISSUE TITLE
Installs wine prefix at ~/.wine, polluting my home directory

### ISSUE THREAD

**Issue by 1player** [flathub/net.lutris.Lutris#284]
By default this Flatpak creates a wine prefix at ~/.wine and install games at ~/Games.

I would rather that Flatpak applications install their stuff inside their data directory, not polluting my home directory with wine prefixes, and ideally game directories as well. Am I missing some option to use more sane defaults? 

I use Flatpak because I want to sandbox applications from the host, the default configuration defeats its purpose completely.

**Comment by strycore** [comment]
Lutris should never create prefixes in ~/.wine. This is a bug with the client itself, open a bug there.
