### ISSUE TITLE
Install Instructions

### ISSUE THREAD

**Issue by nabel0** [flathub/net.lutris.Lutris#286]
On the Lutris Download site i can see the following istructions for the flatpak version:

--> https://lutris.net/downloads

***********************************

Lutris is available in Flathub Beta.
Add the Flathub Beta repository if not already enabled:
flatpak remote-add flathub-beta https://flathub.org/beta-repo/flathub-beta.flatpakrepo
flatpak update --appstream
Install required dependencies from Flathub (non Beta):
flatpak install flathub org.gnome.Platform.Compat.i386 org.freedesktop.Platform.GL32.default org.freedesktop.Platform.GL.default
Install Lutris:
flatpak install flathub-beta net.lutris.Lutris

**********************************

But if i look in the "Discover" store on the Steam Deck i can find the latest Version "0.5.11" also in the "stable" branch of flathub.
More precisely, the current lutris version v0.5.11 is now 2x to find. Once in the beta flatpak repo and once in the "normal" flatpack repo

So i'll guess those instructions on the download page are no longer valid.
We dont need to add the flatpack beta repo anymore.

**Comment by strycore** [comment]
Fixed
