### ISSUE TITLE
Purpose of org.winehq.Wine.* extensions?

### ISSUE THREAD

**Issue by Mershl** [flathub/net.lutris.Lutris#305]
Installing lutris today installs the following three extensions:
`org.winehq.Wine.gecko`
`org.winehq.Wine.mono`
`org.winehq.Wine.DLLs.DXVK`

Just testing with the Wine runner of Lutris these extensions seem to not actually be used.

`org.winehq.Wine.gecko/mono` -> Wine Prefix creation still shows the infamous "Wine could not find a wine-mono package" and "Wine could not find a Gecko package" warning - both harmless, but an indicator that the extensions are not actually used.
`org.winehq.Wine.DLLs.DXVK` -> from the logs it seems that Lutris's own provided DXVK dlls are used instead of the extension's DLLs. Removing the extension shows no effect to the log of launching a game with a Wine runner and everything seems to work as expected.

**Comment by strycore** [comment]
I don't know why these extensions are bundled with the Flatpak but it's true that they are entirely useless in the context of Lutris and should be removed.

**Comment by A6GibKm** [comment]
They are part of building wine. There are benefits for using our own build instead of one packaged by lutris.

**Comment by Mershl** [comment]
Thank you for your feedback @A6GibKm,

> They are part of building wine. There are benefits for using our own build instead of one packaged by lutris.

Is there a usecase or a flatpak-specific requirement for an Flatpak built "System Wine"?

In my testing Lutris does not share the sub-sandbox problem of Flatpak Steam which requires flatpak-specific Wine builds if e.g. the user wants to override Flatpak extensions.

I've not seen any regressions from using Lutris provided Wine builds in Flatpak Lutris and frankly every installer on Lutris.net references an Lutris provided Wine build.

**Comment by A6GibKm** [comment]
> I've not seen any regressions from using Lutris provided Wine builds in Flatpak Lutris and frankly every installer on Lutris.net references an Lutris provided Wine build.

The entire point of flathub is to use stuff built by its CI to have *guaranteed* api and abi compability, the problem is that it is not clear when there will be problems by not doing so. If it is working for someone thats not an indicative of it working for everyone nor it is an indicator that it will continue to work in the future.
