### ISSUE TITLE
Steam missing as a Source - can't install Steam games with Lutris.

### ISSUE THREAD

**Issue by junglized** [flathub/net.lutris.Lutris#314]
**Describe the problem**
As in the title. I installed Lutris and Steam, both flatpak versions from Linux Mint repo. I launched Lutris and couldn't see Steam in Preferences > Sources menu to install games. Only Steam for Windows which wants me to install Steam client with Wine.

**Is it reproducible with native Lutris?**
Same, native Lutris doesn't have Steam as a Source.

**Steps to reproduce**
1. Install any (flatpak or native) version of Lutris
2. Install flatpak version of Steam

**Expected behavior**
See Steam in Preferences > Sources.

**Actual behavior**
Can't see Steam in Preferences > Sources.

**Flatpak info**
`flatpak --version`:

Flatpak 1.12.7

`flatpak --gl-drivers`:

nvidia-525-60-11
default
host

**Comment by lapastillaroja** [comment]
I'm having same problem
PopOS 22.04

**Comment by junglized** [comment]
I solved that issue by installing both Lutris and Steam with .deb pacfkages downloaded directly form corresponding websites. Everything works, apart from slight hiccups, as expected.

**Comment by lapastillaroja** [comment]
Thanks
I ended up doing the same.

**Comment by junglized** [comment]
That sums it up then. Ditch Flatpak, at least for those two apps.
