### ISSUE TITLE
Release 0.5.12 not updating, reset bug

### ISSUE THREAD

**Issue by piperojasjaimes** [flathub/net.lutris.Lutris#317]
I have Lutris 0.5.11 but when I try to update it even for Discover or via console with flatpak update, both sides the SteamDeck gets immediately reset and I am not able to update Lutris, if I try to remove it then is the same, I can not do anything with my current lutris, is there any way to update it and fix it?

**Comment by strycore** [comment]
If you or anyone has this issue, make sure your existing Lutris Flatpak isn't from Flathub Beta.
Removing then re-installing the Flatpak might be the easier route but you can also use the flatpak command line to figure out the cause of the issue. (`flatpak update` should tell you)
