### ISSUE TITLE
Verify ownership on beta.flathub.org

### ISSUE THREAD

**Issue by barthalion** [flathub/net.lutris.Lutris#323]
@strycore,

We're preparing for the launch of beta.flathub.org, and would like to see Lutris verified as maintained by its developers. Currently, I've marked it as such manually, but it would be preferred to use one of the verification features. This can be initiated by logging it at https://beta.flathub.org/login with a GitHub account, pressing "Developer Settings" and following the instructions there.

Please let me know when it's done, so I can remove the manual verification flag.

**Comment by strycore** [comment]
All done, I've completed the verification process.

**Comment by barthalion** [comment]
Thanks!
