### ISSUE TITLE
Update java to 17

### ISSUE THREAD

**Issue by motorto** [flathub/net.lutris.Lutris#343]
**Describe the problem**
Latest minecraft version can't be played because it requires java 17 while the flatpak only brings the java11.

```
This instance is not compatible with Java version 11.
Please switch to one of the following Java versions for this instance:
Java version 17
Go to instance Java settings to change your Java version or disable the Java compatibility check if you know what you're doing.
```

**Comment by strycore** [comment]
What installer did you use?

I used the official installer, it runs without issue. Just had to switch to WASD with Steam Input.

![20230615_204717](https://github.com/flathub/net.lutris.Lutris/assets/280336/2713091a-b4e6-4f67-881e-b939db51e946)

**Comment by motorto** [comment]
Prism launcher

**Comment by strycore** [comment]
I updated the runtime here: https://github.com/flathub/net.lutris.Lutris/pull/344

**Comment by strycore** [comment]
This will be published on Flathub beta soon and will reach Flathub stable when we sync with the master branch
