### ISSUE TITLE
Wine: Vulkan ICD loader contains long warnings and errors in GUI but is functional

### ISSUE THREAD

**Issue by Mershl** [flathub/net.lutris.Lutris#352]
**Describe the problem**
Configure Wine runner, switch to tab `System Options`, enabled `Advanced` options on the top right.
Vulkan ICD loader will contain multiple very long warning entries which stretch the GUI wide.
The tested system does not have an Intel iGPU or dGPU. The list still contains an error for ANV.

![image](https://github.com/flathub/net.lutris.Lutris/assets/520251/0ea9af7c-e6b6-4975-9085-303e8dadb711)

`flatpak run net.lutris.Lutris -d` does not show any issues.

The selection is functional. No issues found ingame.

**Is it reproducible with native Lutris?**

lutris ran through `toolbox` shows the following entries - though this might be misleading:

![image](https://github.com/flathub/net.lutris.Lutris/assets/520251/4b2447f0-d7e0-4c97-8508-20d4a34a88b8)

**Flatpak info**
```
$ flatpak --version
Flatpak 1.15.4
$ flatpak --gl-drivers
default
host
```

**Comment by strycore** [comment]
With Lutris from flathub-beta, the output should be like the native one.

**Comment by Mershl** [comment]
Can confirm, 0.5.14 on flathub looks just like native.
