### ISSUE TITLE
GZdoom fails to start: "Couldn't find matching GLX visual"

### ISSUE THREAD

**Issue by xordspar0** [flathub/net.lutris.Lutris#353]
**Describe the problem**

GZdoom from the zdoom runner fails to start.

**Is it reproducible with native Lutris?**
No.

**Steps to reproduce**
1. Install the Doom shareware version: https://lutris.net/games/doom-1993/
2. Go through the installation process, installing the zdoom runner.
3. When installation is complete, click "Launch".

**Expected behavior**
The game should start normally.

**Actual behavior**
A window pops up that says:

> Failed to create OpenGL window: Couldn't find matching GLX visual

**Flatpak info**
`flatpak --version`

Flatpak 1.15.4

`flatpak --gl-drivers`

default
host

**Comment by strycore** [comment]
The next release will support the GZdoom Flatpak which will solve this issue.

**Comment by xordspar0** [comment]
Ah, sorry. I've been using the working version for over a year and forgot about this issue. Thanks for following up!
