### ISSUE TITLE
SCUMM game not starting, libssh.so.4 missing

### ISSUE THREAD

**Issue by 1player** [flathub/net.lutris.Lutris#360]
Tried running Riven from GOG. Doesn't start, log shows:

```
Started initial process 198 from gamemoderun /var/home/sph/.var/app/net.lutris.Lutris/data/lutris/runners/scummvm/bin/scummvm --extrapath=/var/home/sph/.var/app/net.lutris.Lutris/data/lutris/runners/scummvm/share/scummvm --themepath=/var/home/sph/.var/app/net.lutris.Lutris/data/lutris/runners/scummvm/share/scummvm --aspect-ratio --fullscreen --gfx-mode=3x --path=/var/home/sph/Games/gog/riven-the-sequel-to-myst --language=en --filtering mohawk:riven
Start monitoring process.
/var/home/sph/.var/app/net.lutris.Lutris/data/lutris/runners/scummvm/bin/scummvm: error while loading shared libraries: libssh.so.4: cannot open shared object file: No such file or directory
Monitored process exited.
Initial process has exited (return code: 32512)
All processes have quit
Exit with return code 32512
```

**Comment by jibsaramnim** [comment]
Can confirm I'm experiencing the same thing, on Fedora 38 Silverblue.

**Comment by markoong** [comment]
The Curse of Monkey Island, GOG version: 

> scummvm: error while loading shared libraries: libssh.so.4: cannot open shared object file: No such file or directory
> Monitored process exited.
> Initial process has exited (return code: 32512)

**Comment by cloudrac3r** [comment]
Here's a temporary workaround: [Download libssh.so.4](https://cadence.moe/friends/libssh.so.4) and put it into your `~/.var/app/net.lutris.Lutris/data/lutris/runners/scummvm/lib/` folder next to the other .so files.

Or if you don't want to download executable code from my website, get the file from the Fedora packages like this:

- [Go to the libssh package](https://packages.fedoraproject.org/pkgs/libssh/libssh/)
- Click the blue link in the table next to Fedora 38
- Click on the View Build link near the top
- Download the x86_64 rpm package
- Open it in an unarchiver program
- Extract usr/lib64/libssh.so.4.9.6
- Rename to libssh.so.4
- Put it in `~/.var/app/net.lutris.Lutris/data/lutris/runners/scummvm/lib/` next to the other .so files.

This lets ScummVM games boot in Flatpak Lutris on my computer. Of course, it would be nice if this dependency was either removed or bundled with the official Flatpak.

**Comment by irisdominguez** [comment]
Hi! Another one wiht the same issues. Trying what @cloudrac3r got over the issue with that library, but then it failed for a different library.

While checking, I found a really weird workaround:

1. Remove all the libraries inside the lutris scummvm runner: `rm -r ~/.var/app/net.lutris.Lutris/data/lutris/runners/scummvm/lib`
2. Install scummvm in your system: `sudo apt install scummvm`. Not going to use it, but this way we know that the required libraries are in the system.
3. Soft link to the system libraries: `ln -s /usr/lib/x86_64-linux-gnu ~/.var/app/net.lutris.Lutris/data/lutris/runners/scummvm/lib`
4. The runner still fails from within lutris, with the same issue in the logs. But on the first line of the logs you can see the command that it is supposedly running... and it actually works from terminal!!! `~/.var/app/net.lutris.Lutris/data/lutris/runners/scummvm/bin/scummvm --extrapath=~/.var/app/net.lutris.Lutris/data/lutris/runners/scummvm/share/scummvm --themepath=~/.var/app/net.lutris.Lutris/data/lutris/runners/scummvm/share/scummvm --aspect-ratio --fullscreen --scaler=normal --scale-factor=3 --path=~/Games/beneath-a-steel-sky/ --language=es sky`

I have no idea why it's running from the command and not from within Lutris. I've wasted a lot of time trying to make it work, so I'll use this for now...

**Comment by pioalpha** [comment]
> Hi! Another one wiht the same issues. Trying what @cloudrac3r got over the issue with that library, but then it failed for a different library.
> 
> While checking, I found a really weird workaround:
> 
>     1. Remove all the libraries inside the lutris scummvm runner: `rm -r ~/.var/app/net.lutris.Lutris/data/lutris/runners/scummvm/lib`
> 
>     2. Install scummvm in your system: `sudo apt install scummvm`. Not going to use it, but this way we know that the required libraries are in the system.
> 
>     3. Soft link to the system libraries: `ln -s /usr/lib/x86_64-linux-gnu ~/.var/app/net.lutris.Lutris/data/lutris/runners/scummvm/lib`
> 
>     4. The runner still fails from within lutris, with the same issue in the logs. But on the first line of the logs you can see the command that it is supposedly running... and it actually works from terminal!!! `~/.var/app/net.lutris.Lutris/data/lutris/runners/scummvm/bin/scummvm --extrapath=~/.var/app/net.lutris.Lutris/data/lutris/runners/scummvm/share/scummvm --themepath=~/.var/app/net.lutris.Lutris/data/lutris/runners/scummvm/share/scummvm --aspect-ratio --fullscreen --scaler=normal --scale-factor=3 --path=~/Games/beneath-a-steel-sky/ --language=es sky`
> 
> 
> I have no idea why it's running from the command and not from within Lutris. I've wasted a lot of time trying to make it work, so I'll use this for now...

I copied the libssh.so.4 file you discovered to the folder ~/.var/app/net.lutris.Lutris/data/lutris/runtime/Ubuntu-18.04-x86_64 and ScummVM started working in Lutris.

**Comment by misieck** [comment]
This makes Lutris unusable on Steamdeck. Ver. 0.5.17.

**Comment by strycore** [comment]
As a quick workaround until we push a fix for the flatpak, you can use the Flatpak version of Scummvm which will work fine until we push an update.

**Comment by legluondunet** [comment]
1) in Lutris, uninstall ScummVM runner
2) install Scummvm Flatpak
3) in Lutris, ScummVM options, specify a "custom executable for the runner" org.Scummvm.ScummVM, like this:

![image](https://github.com/user-attachments/assets/0cb90afc-5981-4f81-b0f1-ead139102015)

4) Use Flatseal to manage ScummVM Flatpak access to your games directory

**Comment by Yossefbr** [comment]
cp /usr/lib/libssh.so.4* ~/.var/app/net.lutris.Lutris/data/lutris/runners/scummvm/lib/

this solved it for me
