### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by Victor239** [flathub/net.lutris.Lutris#370]
Changelogs can be displayed on Flathub and within distro app updaters, all that's needed is an `.appdata`/[.metainfo.xml](https://docs.flatpak.org/en/latest/conventions.html#appdata-files) file. 

See these examples of another app's [appdata.xml](https://github.com/flathub/io.github.trigg.discover_overlay/blob/master/io.github.trigg.discover_overlay.appdata.xml), and how their changelog is [displayed on Flathub](https://flathub.org/en-GB/apps/io.github.trigg.discover_overlay).

**Comment by strycore** [comment]
We have a metainfo file and I added the changelog for the next release here: https://github.com/lutris/lutris/commit/9d6eb3b9a0911f3cf0fa47819f35a00c9a7ab406
