### ISSUE TITLE
Lutris flatpak creating application menu shortcuts at the wrong directory, with invalid launchers

### ISSUE THREAD

**Issue by ek-is-anika** [flathub/net.lutris.Lutris#371]
Heya, I have lutris v0.5.13 installed through flatpak, and it seems like if I click "Create application menu shortcut", the shortcut gets created at `~/.var/app/net.lutris.Lutris/data/applications`, and not at `~/.local/share/applications`, even with explicit access to that directory. 
I have tried simply linking it to `~/.local/share/applications`, but they don't have an icon, nor do they work when you launch them. 

I have also tried looking for solutions online, but all I could find were reddit posts that I could not access, because it was marked as NSFW, and a discourse post with no replies, so I have no way of properly fixing this without a dev's help. 
Thanks in advance!

**Comment by A6GibKm** [comment]
Lutris just needs to use the portal. This is a duplicate anyways

**Comment by strycore** [comment]
I think this should fix the issue: https://github.com/lutris/lutris/commit/0531e7f9c67bdf10c4fa46e84ace41af954f10c5

> Lutris just needs to use the portal. 

How is this done?

**Comment by A6GibKm** [comment]
One option is to talk directly via DBus and use this interface https://flatpak.github.io/xdg-desktop-portal/#gdbus-org.freedesktop.portal.DynamicLauncher/

The other option is to use libportal and use something like https://libportal.org/method.Portal.dynamic_launcher_install.html. If you ping me later today, I can try to search for an example of how to load libportal from pygobject, its not hard but not super obvious either.
