### ISSUE TITLE
Lutris change executable folder

### ISSUE THREAD

**Issue by PrzemekSkw** [flathub/net.lutris.Lutris#375]
**Describe the problem**
I try to run Lutris flatpak on steam-headless container in unraid server. I move folders from old installation on archlinux laptop. There was Lutris installed from official repo.
I move my `/home/przemek/Games` to mounted in steam-headless container folder: `/mnt/games/lutris`
Then I move `/home/przemek/.local/share/lutris` to my unraid server to monunted `/mnt/games/` and then to `/.var/app/net.lutris.Lutris/data/lutris`. 
Then I see my old games in Lutris and try to change paths.
When I change from old laptop path to new one: `/mnt/Games/lutris` and click `save` I see path:
`/tmp/.X11-unix/run/doc/da0c2320/`.
When I run game I have error:
`The file /tmp/.X11-unix/run/doc/cd5ff09c/Steelrising.exe could not be found`

**Is it reproducible with native Lutris?**
No

**Expected behavior**
See folders I set in Lutris settings

**Flatpak info**
`flatpak --version` `1.14.4`
`flatpak --gl-drivers` `nvidia-535-113-01   default  host`

Regards.

**Comment by ryryonline** [comment]
Use flatseal to give permissions to those directories.

**Comment by strycore** [comment]
Lutris already provides access to the full filesystem. There is no need to add anything with Flatseal.

**Comment by ryryonline** [comment]
steam-headless is run in a docker on Unraid so it limits access to the filesystem where OPs games are stored. This isn’t a Lutris issue, but rather a docker security feature.
