### ISSUE TITLE
error: No remote refs found similar to ‘flathub-beta’

### ISSUE THREAD

**Issue by rowbawts** [flathub/net.lutris.Lutris#4]
Flathub's regular branch works perfect on my system but after following the readme attached to this repo I can't finish the installation of the Flatpak due to above error the result of flatpak remotes shows its installed

```
Name         Options
fedora       system,oci
flathub      system
flathub-beta system
winepak      system
```
```

           /:-------------:\          solojazz@hardware
        :-------------------::        OS: Fedora 
      :-----------/shhOHbmp---:\      Kernel: x86_64 Linux 5.1.5-300.fc30.x86_64
    /-----------omMMMNNNMMD  ---:     Uptime: 10m
   :-----------sMMMMNMNMP.    ---:    Packages: 1671
  :-----------:MMMdP-------    ---\   Shell: bash 5.0.7
 ,------------:MMMd--------    ---:   Resolution: 1920x1080
 :------------:MMMd-------    .---:   DE: GNOME 
 :----    oNMMMMMMMMMNho     .----:   WM: GNOME Shell
 :--     .+shhhMMMmhhy++   .------/   WM Theme: 
 :-    -------:MMMd--------------:    GTK Theme: Mojave-dark [GTK2/3]
 :-   --------/MMMd-------------;     Icon Theme: McMojave-circle-dark
 :-    ------/hMMMy------------:      Font: Cantarell 11
 :-- :dMNdhhdNMMNo------------;       CPU: Intel Core i7-3930K @ 12x 3.8GHz [34.0°C]
 :---:sdNMMMMNds:------------:        GPU: Radeon RX 580 Series (POLARIS10, DRM 3.30.0, 5.1.5-300.fc30.x86_64, LLVM 8.0.0)
 :------:://:-------------::          RAM: 2278MiB / 15977MiB
 :---------------------://       
```

**Comment by gasinvein** [comment]
What specific command gives you this error?

**Comment by lionirdeadman** [comment]
There's an error in the README,

We tell them to add the repo as system (as you can see above) and then tell them to install as user with `--user` where the repo is not installed.

**Comment by rowbawts** [comment]
> What specific command gives you this error?

flatpak install --user flathub-beta net.lutris.Lutris//Beta

> There's an error in the README,
> 
> We tell them to add the repo as system (as you can see above) and then tell them to install as user with `--user` where the repo is not installed.

Even running without the --user flag it gives the same output.

**Comment by gasinvein** [comment]
I hope we move this instructions to wiki, and fix it there. Sorry for this misguiding.

Also the ref `net.lutris.Lutris//Beta` is erroneous, the branch is `beta`, lowercase.

**Comment by rowbawts** [comment]
Oh yeah just lower cased the B and it works shall I close?

**Comment by gasinvein** [comment]
Leave it open until the instructions are actually fixed, either in wiki or not.
