### ISSUE TITLE
Vulkan not available

### ISSUE THREAD

**Issue by A6GibKm** [flathub/net.lutris.Lutris#41]
Since 6445c9eed9f2a353472093bcd7df62526afb456b Vulkan is not detected on the system. I removed all runtimes from freedesktop-sdk and did a clean install and I got the following error:
```
WARNING  2019-09-06 10:58:39,682 [startup.check_driver:68]:glxinfo is not available on your system, unable to detect driver version
INFO     2019-09-06 10:58:39,682 [startup.check_driver:75]:GPU: 1002:67DF 1458:22F7 using amdgpu drivers
INFO     2019-09-06 10:58:39,683 [startup.check_vulkan:131]:Vulkan is not available or your system isn't Vulkan capable
```
After installing `org.freedesktop.Platform.GL{,32}.default` from flathub-beta (or freedesktop-sdk) the following error appears: 
```
bwrap: Can't mkdir /app/lib/i386-linux-gnu/GL: Read-only file system
error: ldconfig failed, exit status 256
```

**Comment by gasinvein** [comment]
The GL directory is missing from the compat extension. Upstream fix pending https://gitlab.com/freedesktop-sdk/freedesktop-sdk/merge_requests/1715

@LeandroStanger, I believe you shouldn't be that quick to merge things without testing.

**Comment by gasinvein** [comment]
Should be fixed with latest runtime update.
