### ISSUE TITLE
[Wine runner] NoneType object has no attribute 'formatted_playtime'

### ISSUE THREAD

**Issue by Mershl** [flathub/net.lutris.Lutris#421]
# Description
Using the Playtime field on a new locally installed game shows `'NoneType' object has no attribute 'formatted_playtime'`.

First seen on 0.5.17

# Steps to reproduce
1) Click `+`
2) Click `Add locally installed game`
3) Enter a Name: `testgame`
4) Select Runner: `Wine`
5) Enter a Playtime: `3h`

![image](https://github.com/flathub/net.lutris.Lutris/assets/520251/00282cbe-e7e6-4c66-85e7-9a52fd6955f6)

**Comment by danieljohnson2** [comment]
This one is a client issue and should be reported [at the Lutris client repo](https://github.com/lutris/lutris) but I'll go ahead and fix it now.
