### ISSUE TITLE
Missing libFLAC.so.8 when trying to run ScummVM games

### ISSUE THREAD

**Issue by terzag** [flathub/net.lutris.Lutris#422]
When I try to run ScummVM games, I get the following error in the log:
```
Started initial process 1006 from gamemoderun /home/terzag/.var/app/net.lutris.Lutris/data/lutris/runners/scummvm/bin/scummvm --extrapath=/home/terzag/.var/app/net.lutris.Lutris/data/lutris/runners/scummvm/share/scummvm --themepath=/home/terzag/.var/app/net.lutris.Lutris/data/lutris/runners/scummvm/share/scummvm --aspect-ratio --fullscreen --scaler=normal --scale-factor=3 --path=/mnt/data2/Jeux/dreamweb dreamweb
Start monitoring process.
/home/terzag/.var/app/net.lutris.Lutris/data/lutris/runners/scummvm/bin/scummvm: error while loading shared libraries: libFLAC.so.8: cannot open shared object file: No such file or directory
Monitored process exited.
Initial process has exited (return code: 32512)
All processes have quit
Exit with return code 32512
```
I've tried with DreamWeb and Beneath a Steel Sky, which are both freely downloadable from the ScummVM website. It seems to happen with games that don't have FLAC files too (BaSS doesn't).

Using Xubuntu 23.10 which only has libFLAC.so.12 in its repos, if that matters for flatpak apps. But I would assume that the issue comes from a missing library/version from the flatpak runtimes and apps only use libs from them?

Lutris is up to date (0.5.17).
flatpak 1.14.4
flatpak --gl-drivers mentions "default" and "host".

I had originally submitted a bug report for the Lutris client, not sure which one is the proper repo for this: https://github.com/lutris/lutris/issues/5236

**Comment by legluondunet** [comment]
1) in Lutris, uninstall ScummVM runner
2) install Scummvm Flatpak
3) in Lutris, ScummVM options, specify a "custom executable for the runner" org.Scummvm.ScummVM, like this:

![image](https://github.com/user-attachments/assets/0cb90afc-5981-4f81-b0f1-ead139102015)

4) Use Flatseal to manage ScummVM Flatpak access to your games directory

**Comment by QmwJlHuSg9pa** [comment]
Strange -- out of curiosity, I just tested an existing game install (circa v0.5.14) under v0.5.18, and even with step 4 applied, I am getting an unrelated error message `The executable 'scummvm/bin/scummvm' could not be found.`. The game in question was working just fine with the ScummVM Flatpak previously.

**Comment by legluondunet** [comment]
Sorry, I forgot to precise: fixed in latest Git code or in next version
