### ISSUE TITLE
Unable to start Lutris

### ISSUE THREAD

**Issue by zastrixarundell** [flathub/net.lutris.Lutris#424]
**Describe the problem**
Unable to run the Lutris flatpak. Nothing happens on GUI and in terminal I get the follow logs:
```bash
flatpak run net.lutris.Lutris
F: Not sharing "/usr/share/icons" with sandbox: Path "/usr" is reserved by Flatpak
2024-05-18 22:37:10,629: Command 'fluidsynth' not found on your system
qdbus: error while loading shared libraries: libQt5Xml.so.5: cannot open shared object file: No such file or directory
2024-05-18 22:37:11,019: Starting Lutris 0.5.17
Traceback (most recent call last):
  File "/app/lib/python3.11/site-packages/lutris/gui/application.py", line 480, in do_command_line
    init_lutris()
  File "/app/lib/python3.11/site-packages/lutris/startup.py", line 133, in init_lutris
    init_dirs()
  File "/app/lib/python3.11/site-packages/lutris/startup.py", line 48, in init_dirs
    create_folder(directory)
  File "/app/lib/python3.11/site-packages/lutris/util/system.py", line 401, in create_folder
    os.makedirs(path, exist_ok=True)
  File "<frozen os>", line 215, in makedirs
  File "<frozen os>", line 225, in makedirs
OSError: [Errno 30] Read-only file system: '/home/zastrix/.var/app/net.lutris.Lutris/data/icons/hicolor/128x128'
```

I've tried deleting the `~/.var/app/net.lutris.Lutris` and to also `chmod -R 777 ~/.var/app/net.lutris/Lutris`.

Also because of the Qt issue, it's probably a good idea to notify I'm running KDE 6.

**Is it reproducible with native Lutris?**
Immutable system and didn't start native lutris. According to logs it's either access or missing libraries.

**Steps to reproduce**
1. Try to run lutris
2. Doesn't do anything

**Expected behavior**
For Lutris to start.

**Actual behavior**
Doesn't start

**Flatpak info**
```bash
zastrix@main-pc $ flatpak --version
Flatpak 1.15.8

zastrix@main-pc $ flatpak --gl-drivers
default
host
```

**Comment by strycore** [comment]
It says right here what your problem is: 
`OSError: [Errno 30] Read-only file system: '/home/zastrix/.var/app/net.lutris.Lutris/data/icons/hicolor/128x128'`

The only immutable system I use currently is SteamOS and that doesn't have the home folder as read only so there's something wrong with your setup.

**Comment by zastrixarundell** [comment]
It's not read-only though... The folder is created when I run lutris. I've also changed the permission to 777 for the folder insecurely.

**Comment by strycore** [comment]
Well Python inside the Flatpak thinks it is read only. Also, permissions on Flatpaks are not resolved with chmod commands but with something like Flatseal and in any case, you don't need to chmod 777 anything

**Comment by zastrixarundell** [comment]
```bash
zastrix@main-pc $ ~
zastrix@main-pc $ echo "My dummy data" | tee .var/app/net.lutris.Lutris/data/icons/dummy_file
My dummy data
zastrix@main-pc $ cat .var/app/net.lutris.Lutris/data/icons/dummy_file
My dummy data
```

**Comment by strycore** [comment]
you're not running this command from inside a Flatpak so it's a totally different environment.

**Comment by zastrixarundell** [comment]
I've reset the Lutris flatseal and then disabled my global flatpak overrides:

![image](https://github.com/flathub/net.lutris.Lutris/assets/30195425/a65558af-9360-4dc1-979d-9639093b89ee)

But it does seems like a RO FS from inside the container:
```bash
bash-5.2$ pwd
/var/home/zastrix/.var/app/net.lutris.Lutris/data/icons/hicolor
bash-5.2$ touch 128x128
touch: cannot touch '128x128': Read-only file system
```

(This comment is a WIP, I'll just log out of my session and update in a few minutes (I don't want to loose the image)).

**Comment by zastrixarundell** [comment]
Logged out and in, and removed some old global permissions. This is currently the state on flatseal:
![image](https://github.com/flathub/net.lutris.Lutris/assets/30195425/e5897152-21b4-47ec-94d3-7e2151aa1fa6)

Still the same issue.

**Comment by strycore** [comment]
Flatseal is usually for allowing a Flatpak to access folders outside of the Flatpak's own folder. Here, Lutris can't write to it's own folder which is very weird.

Other Flatpaks don't cause similar issues?

**Comment by zastrixarundell** [comment]
I know that flatseal is for allowing it to do stuff, but it's also a great way to see the current permissions.

Other flatpaks don't have the issue, I'm able to download games on the steam flatpak for instance.

**Comment by strycore** [comment]
I'm confused by what's going on here. 

>  I'm able to download games on the steam flatpak for instance.

And you probably would be able to in Lutris since the games are installed outside the flatpak. The problem here is Lutris not being able to download its own icons for the GUI. This has never been a problem before even on immutable OSes like Bazzite, so my ability to assist you further is very limited.

**Comment by zastrixarundell** [comment]
I believe it has nothing to do with the fact that I'm using an immutable distro.

**Comment by strycore** [comment]
yeah, I don't believe the immutable distro is the problem here.
I'm out of ideas...  Do you happen to have another OS / another computer to compare your setup with? 

You could always cheat your way out and run : 

`mkdir -p /home/zastrix/.var/app/net.lutris.Lutris/data/icons/hicolor/128x128/apps` 

and then Lutris should stop complaining...

**Comment by zastrixarundell** [comment]
... might've just been a flatpak issue honestly. I ran the app and it didn't want to work. I've ran that command and it worked. I've then ran `rm -rf ~/.var/app/net.lutris.Lutris`, started lutris and... it worked? Like ???

Oh well standard things for devs I guess...
