### ISSUE TITLE
Fix for amazon games in steam deck flatpack

### ISSUE THREAD

**Issue by shreknel** [flathub/net.lutris.Lutris#433]
As described here: https://github.com/lutris/lutris/issues/5562
There is an issue in the current release of Lutris when accessing amazon games.

I've tried to rebuild the flatpack, but have to after it had downloaded many gbs and started to build pretty low-level libs from source one source file at a time,.I gave up.

Is there any way to access a pre-release flatpack build of Lutris?

Thanks!

**Comment by strycore** [comment]
I got Lutris to build for Flathub Beta and an update is currently building. I will also push another update with some even more up to date code which should fix Amazon Prime issues.

**Comment by legluondunet** [comment]
@shreknel should be fixed in Lutris 0.5.18, could you confirm and close this issue?

**Comment by shreknel** [comment]
Yes, it's fixed. Many thanks
