### ISSUE TITLE
Update runtime to 46

### ISSUE THREAD

**Issue by A6GibKm** [flathub/net.lutris.Lutris#443]
GNOME 45 is soft EOL right now (since the release of GNOME 47.0) and will be marked as EOL at Flathub once 47.1 is released, that would be on the [19th](https://release.gnome.org/calendar/).  Once it is marked as EOL, a message will appear annoying users each time they run `flatpak update`.

The beta branch already uses 46, so it should be a matter of back-porting.

cc @strycore

**Comment by strycore** [comment]
Gosh those runtime updates give Flatpak users *absolutely no break at all*. 

We should update to 47 in preparation of the impending doom that is the deprecation of Runtime 46, which bound to happen in a couple weeks.

**Comment by A6GibKm** [comment]
you can update once a year (e.g. skip a version). It is fine, but sure I already prepared the update to 47 at https://github.com/flathub/net.lutris.Lutris/pull/441.

**Comment by benaryorg** [comment]
Just a quick note that the deprecation notice is now on full display every time users run *flatpak update* now:

```text
Info: runtime org.gnome.Platform branch 45 is end-of-life, with reason:
   The GNOME 45 runtime is no longer supported as of September 18, 2024. Please ask your application developer to migrate to a supported platform.
Info: applications using this runtime:
   net.lutris.Lutris
```

**Comment by strycore** [comment]
It's fine.

**Comment by strycore** [comment]
Our manifest has 47 so closing

**Comment by benaryorg** [comment]
> Our manifest has 47 so closing

To be fair it's only the beta channel that has manifest 47, stable users still get said deprecation notice.

**Comment by strycore** [comment]
Ok, and?

**Comment by benaryorg** [comment]
I take it that you would like me to open a new issue to fix the deprecation warning for what is presumably the majority of users then? A deprecation warning shown to users seems like an actionable issue to me, and this issue being closed despite that makes your last comment appear as if that were out of scope for this issue then, but on the off-chance that that wasn't what you meant I'd like to check back before just blindly opening an issue for that.

**Comment by strycore** [comment]
Just need to wait until 0.5.18 gets released.

**Comment by benaryorg** [comment]
Given that the flatpak distribution of Lutris is not enforced to be in sync with the upstream version, and given that this repository is specifically for the packaging (and issue tracking) of the flatpak distribution via Flathub, I feel like depending on an EoL'd software package which includes several security critical libraries used by the packaged application itself should be a tracked issue that shouldn't be closed until the distribution (which is this repository) has fixed the issue, which in this case means for this issue or another such issue to remain open until the packaging has caught up for affected users.
That's just my opinion, and as you're the maintainer you're free to disagree and run the issue tracker in a different way, or have whatever versioning suits you, but I want to make it very clear that flatpak telling me (verbatim) to "ask your application developer to migrate to a supported platform" whenever I run updates does feel like an open issue that is yet to be resolved, and closing it on the issue tracker leaves a bad taste just the same way as a stalebot automatically closing an issue despite it affecting users.

Anyway, with that I'll unsubscribe from the issue.
Thank you for maintaining free (as in freedom) software.
