### ISSUE TITLE
Flatpak runtime branch is marked end-of-life

### ISSUE THREAD

**Issue by tjvans** [flathub/net.lutris.Lutris#458]
**Describe the problem**
The `runtime org.gnome.Platform branch 45` and `runtime org.gnome.Platform.Compat.i386 branch 45` are marked end-of-life and need to be updated.

**Is it reproducible with native Lutris?**
No, only Flatpak version.

**Steps to reproduce**
1. Install Lutris Flatpak from FlatHub
2. Run `flatpak update` in terminal

**Expected behavior**
Update with no errors.

**Actual behavior**
```
flatpak update
Looking for updates…

Info: runtime org.gnome.Platform branch 45 is end-of-life, with reason:
   The GNOME 45 runtime is no longer supported as of September 18, 2024. Please ask your application developer to migrate to a supported platform.
Info: applications using this runtime:
   net.lutris.Lutris

Info: runtime org.gnome.Platform.Compat.i386 branch 45 is end-of-life, with reason:
   The GNOME 45 runtime is no longer supported as of September 18, 2024. Please ask your application developer to migrate to a supported platform.
Info: applications using this extension:
   net.lutris.Lutris
```

**Flatpak info**
`flatpak --version` 1.15.10
`flatpak --gl-drivers` default host

**Comment by strycore** [comment]
The beta branch which is to be released shortly as the new stable version uses Runtime 47
