### ISSUE TITLE
Lutris doesn't check for loaders in /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/

### ISSUE THREAD

**Issue by p1u3o** [flathub/net.lutris.Lutris#46]
This breaks the Vulkan Loader dropdown, I have both Intel and NVIDIA vulkan devices available so forcing games to use the NVIDIA loader is a pain.

This seems to come from https://github.com/lutris/lutris/blob/master/lutris/sysoptions.py#L25

**Comment by gasinvein** [comment]
Hm, [the vulkan spec](https://vulkan.lunarg.com/doc/sdk/1.1.114.0/linux/loader_and_layer_interface.html) defines way more possible paths for ICDs than Lutris searches in. So not only this flatpak-specific paths are missing. Maybe report this upstream?

**Comment by p1u3o** [comment]
I filed it upstream.

https://github.com/lutris/lutris/issues/2337

**Comment by gasinvein** [comment]
Please try a test build from https://github.com/flathub/net.lutris.Lutris/pull/51#issuecomment-531273511 and check if it fixes the issue for you.

**Comment by p1u3o** [comment]
@gasinvein Working :)

![Screenshot from 2019-09-13 16-09-37-cropped(1)](https://user-images.githubusercontent.com/38067056/64873538-32805400-d641-11e9-9caf-3818a8712f45.jpg)

**Comment by gasinvein** [comment]
Good, merging that PR, then. Don't forget to uninstall the test build!
