### ISSUE TITLE
Update to 0.5.18

### ISSUE THREAD

**Issue by bcmedeiros** [flathub/net.lutris.Lutris#464]
Seeing a message when I open Lutris installed from Flathub:

```
Lutris 0.5.17 is no longer supported. Download 0.5.18 here!
```

**Comment by Mershl** [comment]
@danieljohnson2 the error banner includes a download link that is not really helpful for flatpak lutris users.
what do you think about disabling the banner for flatpak lutris until there's a better method?

![image](https://github.com/user-attachments/assets/6a641040-8147-4138-854d-4a57cd9b31fe)

**Comment by danieljohnson2** [comment]
I agree, and I've pushed that change. I do not have access to close this issue in this repo, however.

**Comment by bcmedeiros** [comment]
What about the actual flathub package update?

**Comment by danieljohnson2** [comment]
I don't have access to that either.

**Comment by Mershl** [comment]
> What about the actual flathub package update?

release is merged to master, should pop up on Flathub very soon

**Comment by bcmedeiros** [comment]
I thought this repo was the one responsible to update the Lutris distribution, so that's why I reported this issue. I'm probably missing something, though.

**Comment by AlmeidaRW** [comment]
0.5.18 Flatpak is now now available, despite it showing up as a refresh of version 0.5.17 in the Discover store.
