### ISSUE TITLE
Lutris stops running when org.freedesktop.Platform.GL.default for Flathub is installed

### ISSUE THREAD

**Issue by Saroufim** [flathub/net.lutris.Lutris#54]
When org.freedesktop.Platform.GL.default is installed from flathub, Lutris stops running and it yields the following error messages:
```
bwrap: Can't mkdir /app/lib/i386-linux-gnu/GL: Read-only file system
error: ldconfig failed, exit status 256
```
Removing org.freedesktop.Platform.GL.default makes Lutris work again.

**Comment by gasinvein** [comment]
Is `org.gnome.Platform.Compat.i386//3.34` installed?

**Comment by Saroufim** [comment]
That was the issue. Thank you very much. Is this a flatpak bug perhaps for not pulling the right dependencies?

**Comment by gasinvein** [comment]
Likely so. This is seems to be a duplicate of #53.
