### ISSUE TITLE
Flatpak install requires sudo

### ISSUE THREAD

**Issue by hovo1990** [flathub/net.lutris.Lutris#58]
When I am trying to install lutris, it requires sudo.

![image](https://user-images.githubusercontent.com/7003230/65965219-529c7980-e46f-11e9-93d1-12f77124f31e.png)

**Comment by Saroufim** [comment]
Is the flathub-beta repository enabled for --system or for --user? 
Try flatpak --user remote-list and check if it's there.

**Comment by hovo1990** [comment]
Just ran the command, it is there
![image](https://user-images.githubusercontent.com/7003230/65973232-0572d480-e47c-11e9-952d-b9340e712e2b.png)

**Comment by Saroufim** [comment]
I think Lutris depends on a few items from flathub. You have the flathub-beta remote enabled for the user and flathub enabled for the system. Can you try enabling regular flathub for --user too?

**Comment by hovo1990** [comment]
Tried it, did not work, It seems I have issues with trying to user flatpak in "user" mode.

![image](https://user-images.githubusercontent.com/7003230/65978369-a49bca00-e484-11e9-816a-fb5dd58f7692.png)

**Comment by Saroufim** [comment]
Then I suggest filing a bug against flatpak itself. Seems like it's a bug with the daemon not the package

**Comment by hovo1990** [comment]
will do, thanks for the help

**Comment by bilelmoussaoui** [comment]
You should never use flatpak with sudo anyway. It uses polkit to handle that.
