### ISSUE TITLE
Blizzard Battle net error tried manual and default

### ISSUE THREAD

**Issue by jatin-cbs** [flathub/net.lutris.Lutris#63]
I used both default (standard) and manual install script on lutris flatpak it shows 

The executable at path /home/SHuRiKeN/Games/battlenet/drive_c/Program Files (x86)/Battle.net/Battle.net.exe can't be found, please check the destination folder.
Some parts of the installation process may have not completed successfully.

This error message everytime. On lutris forums it says it requires some wine dependencies or maybe 32 bit deps that flatpak dont provide yet :(

**Comment by gasinvein** [comment]
Please provide concrete steps to reproduce it.

**Comment by jatin-cbs** [comment]
Sorry closing it then 😑
