### ISSUE TITLE
Consider Giving RW Permissions for Steam

### ISSUE THREAD

**Issue by Saroufim** [flathub/net.lutris.Lutris#65]
In the cases of mod managers, RW permissions might be needed to modify game files from Steam

**Comment by LeandroStanger** [comment]
Steam Flatpak?

**Comment by Saroufim** [comment]
Yes. This is a Steam Flatpak case.

**Comment by strycore** [comment]
We also need to write to the shortcuts file to add Lutris games as non-Steam games.

**Comment by A6GibKm** [comment]
We already have `home` access so this should work with Steam installed natively. I think we are not supporting full compatibility with the flatpak version of steam so I am closing.
