### ISSUE TITLE
Wine Not Running 

### ISSUE THREAD

**Issue by Saroufim** [flathub/net.lutris.Lutris#73]
None of the wine programs can be executed via Lutris. Looking through the logs, this seems to be the culprit "bwrap: execvp /bin/sh: No such file or directory". It's as if wine cannot see the files.

**Comment by gasinvein** [comment]
Please use issue template or at least provide exact steps to reproduce it.

**Comment by Saroufim** [comment]
Running a Game
1 - Launch Lutris
2 - Select any game that is already installed and has previously worked and press play
3 - Notice that nothing happens
4 - Run game from the command line by specifying the same wine version and prefix used by lutris
5 - Game runs

It should also be noted that wine, through Lutris, cannot create a prefix in an empty folder. It can through the command line. Neither winecfg nor winetricks work either.

**Comment by gasinvein** [comment]
Which Lutris flatpak branch you are running? Did you run another one previously?

**Comment by Saroufim** [comment]
I'm running the one from flathub-beta and have been running it for at least the past month exclusively. The issue started appearing 2 weeks ago. Everything worked fine before that.

**Comment by gasinvein** [comment]
How exactly are you running wine from command line?

**Comment by Saroufim** [comment]
Here's an example:

` WINE='/home/user/.var/app/net.lutris.Lutris/data/lutris/runners/wine/lutris-nofshack-4.16-x86_64/bin/wine' WINESERVER='/home/user/.var/app/net.lutris.Lutris/data/lutris/runners/wine/lutris-nofshack-4.16-x86_64/bin/wineserver'  WINEPREFIX='/var/home/user/Games/vortex-mod-manager' /home/user/.var/app/net.lutris.Lutris/data/lutris/runners/wine/lutris-nofshack-4.16-x86_64/bin/wine '/var/home/usert/Games/vortex-mod-manager/drive_c/Program Files/Black Tree Gaming Ltd/Vortex/Vortex.exe' `

**Comment by gasinvein** [comment]
And the same prebuilt wine version doesn't work if run from Lutris app? Can you please run Lutris from command line and post it's output (when you run wine from it).

**Comment by Saroufim** [comment]
Here is the [output](https://paste.fedoraproject.org/paste/FuoicjeZEDOwa3b3kKrNvw)

**Comment by gasinvein** [comment]
Weird. Does it happen with the lutris runtime explicitly disabled?

**Comment by Saroufim** [comment]
Yes it does

**Comment by gasinvein** [comment]
Can you please try it with a clean app data directory? Move `~/.var/app/net.lutris.Lutris` directry somewhere else (or backup and delete it) and launch Lutris after that.

**Comment by Saroufim** [comment]
I deleted it and had it recreated. I'm still running into the same "File not found" problem.

**Comment by gasinvein** [comment]
Here is a native wine build https://github.com/flathub/flathub/pull/1060#issuecomment-551938001 that should work with current Lutris beta build. Can you try with it?

**Comment by gasinvein** [comment]
@Saroufim Are you on Silverblue? If so, there might be no `/home` symlink in flatpak sandbox and, thus, _really_ no such file like `/home/User/Games/...`

**Comment by Saroufim** [comment]
Yes I am on Silverblue but it worked fine before and I haven't switched distributions for over a year. What changed now?

**Comment by gasinvein** [comment]
So is there `/home` directory or symlink in the flatpak sandbox?

**Comment by Saroufim** [comment]
It yields `/home: symbolic link to var/home`
Here's a little bit of extra digging:
`flatpak run --command=bash net.lutris.Lutris
[📦 net.lutris.Lutris ~]$ echo $HOME
/home/user
[📦 net.lutris.Lutris ~]$ Running /home/user/.var/app/net.lutris.Lutris/data/lutris/runners/wine/lutris-lol-4.17-x86_64/bin/wine /var/home/user/Games/league-of-legends/drive_c/Riot Games/League of Legends/LeagueClient.exe
bash: Running: orden no encontrada
[📦 net.lutris.Lutris ~]$ /home/user/.var/app/net.lutris.Lutris/data/lutris/runners/wine/lutris-lol-4.17-x86_64/bin/wine /var/home/user/Games/league-of-legends/drive_c/Riot Games/League of Legends/LeagueClient.exe
bash: /home/user/.var/app/net.lutris.Lutris/data/lutris/runners/wine/lutris-lol-4.17-x86_64/bin/wine: No existe el fichero o el directorio
[📦 net.lutris.Lutris ~]$ cd ~/.var/app/net.lutris.Lutris
[📦 net.lutris.Lutris net.lutris.Lutris]$ cd ~/.var/app/net.lutris.Lutris/data/lutris/runners/wine/
[📦 net.lutris.Lutris wine]$ ls
lutris-4.12.1-x86_64  lutris-lol-4.17-x86_64  lutris-nofshack-4.19-x86_64
[📦 net.lutris.Lutris wine]$ /home/user/.var/app/net.lutris.Lutris/data/lutris/runners/wine/lutris-lol-4.17-x86_64/bin/wine /var/home/user/Games/league-of-legends/drive_c/Riot Games/League of Legends/LeagueClient.exe
bash: /home/user/.var/app/net.lutris.Lutris/data/lutris/runners/wine/lutris-lol-4.17-x86_64/bin/wine: No existe el fichero o el directorio
[📦 net.lutris.Lutris wine]$ cd lutris-lol-4.17-x86_54
bash: cd: lutris-lol-4.17-x86_54: No existe el fichero o el directorio
[📦 net.lutris.Lutris wine]$ cd lutris-lol-4.17-x86_64
[📦 net.lutris.Lutris lutris-lol-4.17-x86_64]$ ls
bin  lib  lib64  share
[📦 net.lutris.Lutris lutris-lol-4.17-x86_64]$ cd bin
[📦 net.lutris.Lutris bin]$ ls
function_grep.pl  regsvr32	    wineboot	 winedbg   winemaker	   wmc
msidb		  widl		    winebuild	 winedump  winemine	   wrc
msiexec		  wine		    winecfg	 winefile  winepath
notepad		  wine64	    wineconsole  wineg++   wine-preloader
regedit		  wine64-preloader  winecpp	 winegcc   wineserver
`

**Comment by gasinvein** [comment]
Is `org.gnome.Platform.Compat.i386//3.34` installed?

**Comment by Saroufim** [comment]
That solved it, thank you!

**Comment by gasinvein** [comment]
Meeh. You've run https://github.com/flathub/net.lutris.Lutris/issues/73#issuecomment-551843057 on the host, not in flatpak sandbox. That completely misled me.

**Comment by Saroufim** [comment]
Yeah I should have clarified that. My apologies.
