### ISSUE TITLE
Discussion with Lutris devs

### ISSUE THREAD

**Issue by tannisroot** [flathub/net.lutris.Lutris#74]
Hey, can somebody who maintains this repo join Lutris's Discord server?
There are some serious issues with this that need to be discussed.

**Comment by gasinvein** [comment]
What channel/room?

**Comment by tannisroot** [comment]
Ping me there and I'll add you to a private channel.

**Comment by gasinvein** [comment]
I'd rather prefer to discuss issues here, theme may be other interested people.

**Comment by RobLoach** [comment]
👋
