### ISSUE TITLE
Games folder cannot be customized

### ISSUE THREAD

**Issue by dariox86** [flathub/net.lutris.Lutris#79]
Flatpak Lutris does not support Games path customization. If a path other than ~/[USER NAME]/Games is chosen, games won't be installed.

**Comment by gasinvein** [comment]
You have to allow access to that folder first, via e.g. 
`flatpak override --filesystem=/path/to/your/Folder net.lutris.Lutris`

**Comment by dariox86** [comment]
OK. Isn't it better to have a Games folder inside the Lutris flatpak by default?

**Comment by dariox86** [comment]
Do I need a special permission in place even if I want to move the folder inside ~/.var/app/net.lutris.Lutris/data/lutris?

**Comment by gasinvein** [comment]
>Isn't it better to have a Games folder inside the Lutris flatpak by default?

Maybe. But it would have several drawbacks.

>Do I need a special permission in place even if I want to move the folder inside >~/.var/app/net.lutris.Lutris/data/lutris?

No, a flatpak app always has read-write access to corresponding directory under `~/.var/app/`.

**Comment by dariox86** [comment]
Thank you. I guess the issue can be closed.

**Comment by dariox86** [comment]
I have a couple more questions. When I move Games elsewhere, ~/[USER NAME]/Games is recreated regardless of the specified path. Is there a way to suppress this behavior? What are the possible drawbacks with having a Games folder in a different path?

**Comment by gasinvein** [comment]
`~/Games` is re-created because flatpak is told to do so, see
https://github.com/flathub/net.lutris.Lutris/blob/88926347f863533ac1ac14e477443f9fba0cc912/net.lutris.Lutris.yml#L19
If this empty folder is unwanted, override the permission with `--nofilesystem=~/Games`.

**Comment by dariox86** [comment]
OK. Thank you.
