### ISSUE TITLE
D9VK: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by LeandroStanger** [flathub/net.lutris.Lutris#83]
**Describe the problem**
![Captura de tela de 2019-11-30 09-54-53](https://user-images.githubusercontent.com/26097419/69900994-c23cc100-1359-11ea-8491-30651a4a3863.png)

**Steps to reproduce**
1.Install League of Legends
2.Play League of Legends

**Flatpak info**
`flatpak --version`
Flatpak 1.5.0
`flatpak --gl-drivers`
default
host

**Comment by dariox86** [comment]
D9VX was merged into upstream DXVK, see [here](https://www.phoronix.com/scan.php?page=news_item&px=D9VK-Merges-Into-DXVK).

**Comment by strycore** [comment]
this can be closed, we no longer ship d9vk
