### ISSUE TITLE
I can't open Lutris

### ISSUE THREAD

**Issue by FelmenExDD** [flathub/net.lutris.Lutris#91]
When I start Lutris, it does not enter and this message appears in the terminal "2020-02-23 10:10:49,118: Couldn't find a terminal emulator.'

**Comment by A6GibKm** [comment]
My log is:

```
2020-02-23 11:31:47,758: Couldn't find a terminal emulator.
2020-02-23 11:31:48,135: Running Lutris 0.5.4
2020-02-23 11:31:48,135: Using X.Org
2020-02-23 11:31:48,135: Running Mesa driver 19.3.3 on Radeon RX 570 Series (POLARIS10, DRM 3.36.0, 5.5.5-200.fc31.x86_64, LLVM 9.0.0) (0x67df)
2020-02-23 11:31:48,135: GPU: 1002:67DF 1458:22F7 using amdgpu drivers
WARNING: Experimental compiler backend enabled. Here be dragons! Incorrect rendering, GPU hangs and/or resets are likely
2020-02-23 11:31:48,222: Vulkan is supported
2020-02-23 11:31:48,223: Updating DXVK versions
Traceback (most recent call last):
  File "/app/lib/python3.7/site-packages/lutris/gui/application.py", line 173, in do_activate
    self.window = LutrisWindow(application=self)
  File "/app/lib/python3.7/site-packages/lutris/gui/lutriswindow.py", line 102, in __init__
    self.game_store = self.get_store()
  File "/app/lib/python3.7/site-packages/lutris/gui/lutriswindow.py", line 321, in get_store
    self.show_installed_first,
  File "/app/lib/python3.7/site-packages/lutris/gui/views/store.py", line 133, in __init__
    self.modelsort = Gtk.TreeModelSort.sort_new_with_model(self.modelfilter)
AttributeError: type object 'TreeModelSort' has no attribute 'sort_new_with_model'
2020-02-23 11:31:49,144: Updating D9VK versions
```

This happens with or without mesa-aco.

**Comment by A6GibKm** [comment]
See https://github.com/lutris/lutris/issues/2554

**Comment by Chip000** [comment]
> My log is:
> 
> ```
> 2020-02-23 11:31:47,758: Couldn't find a terminal emulator.
> 2020-02-23 11:31:48,135: Running Lutris 0.5.4
> 2020-02-23 11:31:48,135: Using X.Org
> 2020-02-23 11:31:48,135: Running Mesa driver 19.3.3 on Radeon RX 570 Series (POLARIS10, DRM 3.36.0, 5.5.5-200.fc31.x86_64, LLVM 9.0.0) (0x67df)
> 2020-02-23 11:31:48,135: GPU: 1002:67DF 1458:22F7 using amdgpu drivers
> WARNING: Experimental compiler backend enabled. Here be dragons! Incorrect rendering, GPU hangs and/or resets are likely
> 2020-02-23 11:31:48,222: Vulkan is supported
> 2020-02-23 11:31:48,223: Updating DXVK versions
> Traceback (most recent call last):
>   File "/app/lib/python3.7/site-packages/lutris/gui/application.py", line 173, in do_activate
>     self.window = LutrisWindow(application=self)
>   File "/app/lib/python3.7/site-packages/lutris/gui/lutriswindow.py", line 102, in __init__
>     self.game_store = self.get_store()
>   File "/app/lib/python3.7/site-packages/lutris/gui/lutriswindow.py", line 321, in get_store
>     self.show_installed_first,
>   File "/app/lib/python3.7/site-packages/lutris/gui/views/store.py", line 133, in __init__
>     self.modelsort = Gtk.TreeModelSort.sort_new_with_model(self.modelfilter)
> AttributeError: type object 'TreeModelSort' has no attribute 'sort_new_with_model'
> 2020-02-23 11:31:49,144: Updating D9VK versions
> ```
> 
> This happens with or without mesa-aco.

Same here. I guess we need to wait for a patched rebuild of package.

**Comment by tinywrkb** [comment]
In the meantime, we can downgrade the runtime

```
flatpak --user update --commit=adc68c54d15bf810a2bbf0b87808f268586d7471046aa1a5af14b056ebe45876 org.gnome.Platform/x86_64/3.34
```
Make sure to kill every running lutirs process before relaunching it.

**Comment by Porkepix** [comment]
On Arch, issue seemed fixed with the latest minor revision of the `gtk3` package. That's a shame such things happen on minor revisions…
