### ISSUE TITLE
After latest update, cannot run any Application, get failed to execute process.

### ISSUE THREAD

**Issue by hovo1990** [flathub/net.lutris.Lutris#95]
**Describe the problem**
A clear and concise description of the problem.

After updating flatpak version of Lutris, I get "Failed to execute process. Check that the file exists."

**Is it reproducible with native Lutris?**
I have not tried native Lutris

**Steps to reproduce**
1. Update Lutris
2. trying to run any lutris app

**Expected behavior**
To run battle.net, Epic Store

**Actual behavior**
for Battle: net 
Running /home/john1990/.var/app/net.lutris.Lutris/data/lutris/runners/wine/lutris-5.0-x86_64/bin/wine /media/Work/Lutris_folder/overwatch/drive_c/Program Files (x86)/Battle.net/Battle.net.exe --exec=launch Pro
Failed to execute process. Check that the file exists

Running /home/john1990/.var/app/net.lutris.Lutris/data/lutris/runners/wine/lutris-5.0-x86_64/bin/wine /media/Work/Lutris_folder/epic-games-store/drive_c/Program Files (x86)/Epic Games/Launcher/Portal/Binaries/Win32/EpicGamesLauncher.exe -opengl
Failed to execute process. Check that the file exists

**Flatpak info**
`flatpak --version` :
 Flatpak 1.6.2

`flatpak --gl-drivers`:

nvidia-440-44
default
host

**Comment by A6GibKm** [comment]
Two things that could cause this:
You might need to add sandbox permission to open your drive 'Work' or that you need to install org.gnome.Platform.Compat.i386//3.36.

**Comment by hovo1990** [comment]
Thanks for the help.
Installing by running flatpak install --system flathub org.gnome.Platform.Compat.i386//3.36, fixed the problem.
